/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DBANC;

import Proveedores.*;
import ConexionBD.Conexion;

import com.microsoft.sqlserver.jdbc.SQLServerDataSource;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mike
 */
public class DBClientes extends javax.swing.JPanel {

    /**
     * Creates new form Proveedores_Principal
     */

    
    public DBClientes() {
        initComponents();
        txtID.setVisible(false);
      //  lbl_id.setVisible(false);
        lblmsgwarning.setVisible(false);
    }
    
        static int confirmacion;
    public String VALORPROV; //Ya sea lo que sea escrito en el txt de busqueda se generara el query 
    public String IDPROV;
    public String NOMPROV;
    public String RFCPROV;
    public String NOMCALLEPROV;
    public String NIPROV;
    public String NEPROV;
    public String ESTPROV;
    public String MUNPROV;
    public String COLPROV;
    public String CPPROV;    
    public String TELPROV;
    public String EMAILPROV;
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void AnadirDomicilio() throws SQLException{
        Statement stm=Conexion.getConexion().createStatement();
       /* ResultSet rs=stm.executeQuery("select top(1)  NumProveedor from Proveedores order by NumProveedor desc");
        if(rs.next()){
             IDPROV=rs.getString(1);
             System.out.println(IDPROV);
             JOptionPane.showMessageDialog(null,"Su identificador es:"+IDPROV);
             rs=stm.executeQuery("insert into DomProveedores values('"+Integer.parseInt(IDPROV)+"','"+NOMCALLEPROV+"','"+NEPROV+"','"+NIPROV+"','"+ESTPROV+"','"+MUNPROV+"','"+COLPROV+"','"+CPPROV+"','"+Integer.parseInt(TELPROV)+"','"+EMAILPROV+"')");
        }*/
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        txtID1 = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtTel3 = new javax.swing.JTextField();
        txtRFC2 = new javax.swing.JTextField();
        txtRFC1 = new javax.swing.JTextField();
        txtID2 = new javax.swing.JTextField();
        txtID3 = new javax.swing.JTextField();
        txtID4 = new javax.swing.JTextField();
        txtID5 = new javax.swing.JTextField();
        txtID6 = new javax.swing.JTextField();
        txtID7 = new javax.swing.JTextField();
        txtID8 = new javax.swing.JTextField();
        txtID9 = new javax.swing.JTextField();
        txtID10 = new javax.swing.JTextField();
        txtRFC3 = new javax.swing.JTextField();
        txtID11 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPEditar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPAdd = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPDelete = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pnl_limpar = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        JPCB = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPBuscar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        lblmsgwarning = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(950, 550));

        jPanel1.setBackground(new java.awt.Color(140, 140, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 390, -1));

        txtID.setEditable(false);
        txtID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 390, -1));

        txtID1.setEditable(false);
        txtID1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, -1));
        jPanel1.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, -1));

        txtTel3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTel3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtTel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, -1));

        txtRFC2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRFC2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFC2KeyTyped(evt);
            }
        });
        jPanel1.add(txtRFC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 110, -1));

        txtRFC1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRFC1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFC1KeyTyped(evt);
            }
        });
        jPanel1.add(txtRFC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 110, -1));

        txtID2.setEditable(false);
        txtID2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, -1));

        txtID3.setEditable(false);
        txtID3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 430, -1));

        txtID4.setEditable(false);
        txtID4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID4ActionPerformed(evt);
            }
        });
        jPanel1.add(txtID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 160, -1));

        txtID5.setEditable(false);
        txtID5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID5ActionPerformed(evt);
            }
        });
        jPanel1.add(txtID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, -1));

        txtID6.setEditable(false);
        txtID6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID6ActionPerformed(evt);
            }
        });
        jPanel1.add(txtID6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 160, -1));

        txtID7.setEditable(false);
        txtID7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID7ActionPerformed(evt);
            }
        });
        jPanel1.add(txtID7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 160, -1));

        txtID8.setEditable(false);
        txtID8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID8ActionPerformed(evt);
            }
        });
        jPanel1.add(txtID8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 160, -1));

        txtID9.setEditable(false);
        txtID9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID9ActionPerformed(evt);
            }
        });
        jPanel1.add(txtID9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 160, -1));

        txtID10.setEditable(false);
        txtID10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID10ActionPerformed(evt);
            }
        });
        jPanel1.add(txtID10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 160, -1));

        txtRFC3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRFC3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFC3KeyTyped(evt);
            }
        });
        jPanel1.add(txtRFC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 110, -1));

        txtID11.setEditable(false);
        txtID11.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID11ActionPerformed(evt);
            }
        });
        jPanel1.add(txtID11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, -1));

        jPanel5.setBackground(new java.awt.Color(107, 190, 249));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPEditar.setBackground(new java.awt.Color(107, 190, 249));
        jPEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPEditarMouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-editar-50.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPEditarLayout = new javax.swing.GroupLayout(jPEditar);
        jPEditar.setLayout(jPEditarLayout);
        jPEditarLayout.setHorizontalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPEditarLayout.setVerticalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEditarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14))
        );

        jPanel5.add(jPEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, -1));

        jPAdd.setBackground(new java.awt.Color(107, 190, 249));
        jPAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPAddMouseExited(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-añadir-usuario-masculino-50.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPAddLayout = new javax.swing.GroupLayout(jPAdd);
        jPAdd.setLayout(jPAddLayout);
        jPAddLayout.setHorizontalGroup(
            jPAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAddLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPAddLayout.setVerticalGroup(
            jPAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAddLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.add(jPAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 90, -1));

        jPDelete.setBackground(new java.awt.Color(107, 190, 249));
        jPDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPDeleteMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-borrar-para-siempre-50.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPDeleteLayout = new javax.swing.GroupLayout(jPDelete);
        jPDelete.setLayout(jPDeleteLayout);
        jPDeleteLayout.setHorizontalGroup(
            jPDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDeleteLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(16, 16, 16))
        );
        jPDeleteLayout.setVerticalGroup(
            jPDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDeleteLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel5.add(jPDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 90, 60));

        pnl_limpar.setBackground(new java.awt.Color(107, 190, 249));
        pnl_limpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_limparMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_limparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_limparMouseExited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-escoba-50.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnl_limparLayout = new javax.swing.GroupLayout(pnl_limpar);
        pnl_limpar.setLayout(pnl_limparLayout);
        pnl_limparLayout.setHorizontalGroup(
            pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limparLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl_limparLayout.setVerticalGroup(
            pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limparLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel5.add(pnl_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 100, 50));

        jPanel6.setBackground(new java.awt.Color(107, 190, 249));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-tabla-40.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(44, 44, 44))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 130, 50));

        jLabel20.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel20.setText("MODIFICAR DATOS BANCARIOS ");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel21.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel21.setText("MOSTRAR INFORMACIÓN");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, -1));

        jLabel23.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel23.setText("LIMPIAR FORMULARIO");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        jLabel24.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel24.setText("INGRESAR DATOS BANCARIOS");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        jLabel25.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel25.setText("QUITAR DATOS BANCARIOS");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Antique Olive", 1, 24)); // NOI18N
        jLabel18.setText("DATOS BANCARIOS DE CLIENTES");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPCB.setBackground(new java.awt.Color(140, 140, 140));

        jPanel4.setBackground(new java.awt.Color(140, 140, 140));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jPBuscar.setBackground(new java.awt.Color(140, 140, 140));
        jPBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPBuscarMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-búsqueda-50 (1).png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPBuscarLayout = new javax.swing.GroupLayout(jPBuscar);
        jPBuscar.setLayout(jPBuscarLayout);
        jPBuscarLayout.setHorizontalGroup(
            jPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBuscarLayout.setVerticalGroup(
            jPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        lblmsgwarning.setFont(new java.awt.Font("Rockwell", 3, 12)); // NOI18N
        lblmsgwarning.setForeground(new java.awt.Color(255, 0, 51));
        lblmsgwarning.setText("¡DEBES COLOCAR INFORMACIÓN PARA GENERAR UNA BUSQUEDA!");

        javax.swing.GroupLayout JPCBLayout = new javax.swing.GroupLayout(JPCB);
        JPCB.setLayout(JPCBLayout);
        JPCBLayout.setHorizontalGroup(
            JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPCBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmsgwarning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPCBLayout.setVerticalGroup(
            JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPCBLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JPCBLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(JPCBLayout.createSequentialGroup()
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblmsgwarning))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // Busqueda de informacion mediante ID, NOMBRE O RFC

       
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
      
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtTel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTel3ActionPerformed

    private void txtRFC1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFC1KeyTyped
      /*  if(txtRFC.getText().length() >= 13)
        {
            evt.consume();
        }*/
    }//GEN-LAST:event_txtRFC1KeyTyped

    private void jPBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBuscarMouseExited
        jPBuscar.setBackground(new java.awt.Color(140,140,140));
    }//GEN-LAST:event_jPBuscarMouseExited

    private void jPBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBuscarMouseEntered
        jPBuscar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPBuscarMouseEntered

    private void jPBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBuscarMouseClicked
        /* Aqui es donde se generara la busqueda

        VALORPROV=txtsearch.getText();
        if(VALORPROV.equals(" "))
        {
            lblmsgwarning.setVisible(true);
        }
        else
        {
            lblmsgwarning.setVisible(false);

            txtID.setVisible(true);
            lbl_id.setVisible(true);
            SQLServerDataSource con = new SQLServerDataSource();
            con.setServerName("localhost");
            con.setDatabaseName("Gestion4F");
            con.setUser("4FAdmin"); //CAMBIO
            con.setPassword("CuatroF");
            con.setPortNumber(1433);

            String url = "select NumProveedor"
            + ",Nombre, "
            + "RFC, "
            + "Nombre_Calle, "
            + "Num_Int, "
            + "Num_Ext, "
            + "Estado, "
            + "Municipio, "
            + "Colonia, "
            + "CP, "
            + "Telefono, "
            + "email "
            + "FROM Proveedores inner join DomProveedores on Proveedores.NumProveedor=DomProveedores.Num_Proveedor "
            + "where NumProveedor like '%"+VALORPROV+"%'";
            try {
                Connection cn = con.getConnection();
                PreparedStatement ps = cn.prepareStatement(url);
                ResultSet rst = ps.executeQuery();
                //Statement stm = Conexion.getConexion().createStatement();
                /*ResultSet rst  = stm.executeQuery("select NumProveedor"
                    + ",Nombre, "
                    + "RFC, "
                    + "Nombre_Calle, "
                    + "Num_Int, "
                    + "Num_Ext, "
                    + "Estado, "
                    + "Municipio, "
                    + "Colonia, "
                    + "CP, "
                    + "Telefono, "
                    + "email "
                    + "FROM Proveedores inner join DomProveedores on Proveedores.NumProveedor=DomProveedores.Num_Proveedor "
                    + "where NumProveedor like '%"+VALORPROV+"%'");-- AQUI ES DONDE TIENES QUE CERRAR 

                while(rst.next())
                {
                    IDPROV=rst.getString(1);
                    NOMPROV=rst.getString(2);
                    RFCPROV=rst.getString(3);
                    NOMCALLEPROV=rst.getString(4);
                    NIPROV=rst.getString(5);
                    NEPROV=rst.getString(6);
                    ESTPROV=rst.getString(7);
                    MUNPROV=rst.getString(8);
                    COLPROV=rst.getString(9);
                    CPPROV =rst.getString(10);
                    TELPROV=rst.getString(11);
                    EMAILPROV=rst.getString(12);

                    txtID.setText(IDPROV.trim());
                    txtNom.setText(NOMPROV.trim());
                    txtRFC.setText(RFCPROV.trim());
                    txtCALLE.setText(NOMCALLEPROV.trim());
                    txtNI.setText(NIPROV.trim());
                    txtNEX.setText(NEPROV.trim());
                    txtEstado.setText(ESTPROV.trim());
                    txtMunicipio1.setText(MUNPROV.trim());
                    txtCOL.setText(COLPROV.trim());
                    txtCP.setText(CPPROV.trim());
                    txtTel.setText(TELPROV.trim());
                    txtemail.setText(EMAILPROV.trim());

                }

            } catch (SQLException ex) {
                Logger.getLogger(DBProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/
    }//GEN-LAST:event_jPBuscarMouseClicked

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(Color.red);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        /*try {
            // TODO add your handling code here:

            TGeneral tg = new TGeneral();
            tg.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DBClientes.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jPanel6MouseClicked

    private void pnl_limparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limparMouseExited
        pnl_limpar.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_pnl_limparMouseExited

    private void pnl_limparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limparMouseEntered
        pnl_limpar.setBackground(Color.red);
    }//GEN-LAST:event_pnl_limparMouseEntered

    private void pnl_limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limparMouseClicked
        // TODO add your handling code here:
        limpiar();
        txtID.setVisible(false);
        //lbl_id.setVisible(false);
    }//GEN-LAST:event_pnl_limparMouseClicked

    private void jPDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDeleteMouseExited
        jPDelete.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_jPDeleteMouseExited

    private void jPDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDeleteMouseEntered
        jPDelete.setBackground(Color.red);
    }//GEN-LAST:event_jPDeleteMouseEntered

    private void jPDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDeleteMouseClicked
        /* Eleminacion de un proveedor
        DDatos d=new DDatos();
        IDPROV=txtID.getText();
        NOMPROV=txtNom.getText();
        RFCPROV=txtRFC.getText();
        NOMCALLEPROV=txtCALLE.getText();
        NIPROV=txtNI.getText();
        NEPROV=txtNEX.getText();
        ESTPROV=txtEstado.getText();
        MUNPROV=txtMunicipio1.getText();
        COLPROV=txtCOL.getText();
        CPPROV=txtCP.getText();
        TELPROV=txtTel.getText();
        EMAILPROV=txtemail.getText();
        d.jID.setText(IDPROV);
        d.jNOM.setText(NOMPROV);
        d.jRFC.setText(RFCPROV);
        d.setVisible(true);*/
    }//GEN-LAST:event_jPDeleteMouseClicked

    private void jPAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAddMouseExited
        jPAdd.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_jPAddMouseExited

    private void jPAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAddMouseEntered
        jPAdd.setBackground(Color.red);
    }//GEN-LAST:event_jPAddMouseEntered

    private void jPAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAddMouseClicked
        /*Agregar datos
        NOMPROV=txtNom.getText();
        RFCPROV=txtRFC.getText();
        NOMCALLEPROV=txtCALLE.getText();
        NIPROV=txtNI.getText();
        NEPROV=txtNEX.getText();
        ESTPROV=txtEstado.getText();
        MUNPROV=txtMunicipio1.getText();
        COLPROV=txtCOL.getText();
        CPPROV=txtCP.getText();
        TELPROV=txtTel.getText();
        EMAILPROV=txtemail.getText();
        try
        {

            Statement stm=Conexion.getConexion().createStatement();
            ResultSet rs=stm.executeQuery("select * from Proveedores where RFC like '%"+RFCPROV+"%' or Nombre ='"+NOMPROV+"'");
            if (rs.next()==false)
            {
                rs=stm.executeQuery("insert into Proveedores (Nombre, RFC) values ('"+NOMPROV+"','"+RFCPROV+"')");

                JOptionPane.showMessageDialog(null,"Su operación exitosa!");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Su operación no puede realizarse!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            AnadirDomicilio();
        } catch (SQLException ex) {
            Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }*/
       /* ADatos ad=new ADatos();
        IDPROV=txtID.getText();
        NOMPROV=txtNom.getText();
        RFCPROV=txtRFC.getText();
        NOMCALLEPROV=txtCALLE.getText();
        NIPROV=txtNI.getText();
        NEPROV=txtNEX.getText();
        ESTPROV=txtEstado.getText();
        MUNPROV=txtMunicipio1.getText();
        COLPROV=txtCOL.getText();
        CPPROV=txtCP.getText();
        TELPROV=txtTel.getText();
        EMAILPROV=txtemail.getText();

        ad.txtNom.setText(NOMPROV);
        ad.txtID.setText(IDPROV);
        ad.txtRFC.setText(RFCPROV);
        ad.txtNC.setText(NOMCALLEPROV);
        ad.txtNI.setText(NIPROV);
        ad.txtNE.setText(NEPROV);
        ad.txtEST.setText(ESTPROV);
        ad.txtMUN.setText(MUNPROV);
        ad.txtCOL.setText(COLPROV);
        ad.txtCP.setText(CPPROV);
        ad.txtTEL.setText(TELPROV);
        ad.txtCE.setText(EMAILPROV);
        ad.setVisible(true);*/
    }//GEN-LAST:event_jPAddMouseClicked

    private void jPEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEditarMouseExited
        jPEditar.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_jPEditarMouseExited

    private void jPEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEditarMouseEntered
        jPEditar.setBackground(Color.red);
    }//GEN-LAST:event_jPEditarMouseEntered

    private void jPEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEditarMouseClicked
        /* Editar la informacion
        EditDatos d= new EditDatos();
        IDPROV=txtID.getText();
        NOMPROV=txtNom.getText();
        RFCPROV=txtRFC.getText();
        NOMCALLEPROV=txtCALLE.getText();
        NIPROV=txtNI.getText();
        NEPROV=txtNEX.getText();
        ESTPROV=txtEstado.getText();
        MUNPROV=txtMunicipio1.getText();
        COLPROV=txtCOL.getText();
        CPPROV=txtCP.getText();
        TELPROV=txtTel.getText();
        EMAILPROV=txtemail.getText();

        d.txtNom.setText(NOMPROV);
        d.txtID.setText(IDPROV);
        d.txtRFC.setText(RFCPROV);
        d.txtNC.setText(NOMCALLEPROV);
        d.txtNI.setText(NIPROV);
        d.txtNE.setText(NEPROV);
        d.txtEST.setText(ESTPROV);
        d.txtMUN.setText(MUNPROV);
        d.txtCOL.setText(COLPROV);
        d.txtCP.setText(CPPROV);
        d.txtTEL.setText(TELPROV);
        d.txtCE.setText(EMAILPROV);
        d.setVisible(true);*/
    }//GEN-LAST:event_jPEditarMouseClicked

    private void txtRFC2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFC2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFC2KeyTyped

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID2ActionPerformed

    private void txtID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID3ActionPerformed

    private void txtID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID4ActionPerformed

    private void txtID5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID5ActionPerformed

    private void txtID6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID6ActionPerformed

    private void txtID7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID7ActionPerformed

    private void txtID8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID8ActionPerformed

    private void txtID9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID9ActionPerformed

    private void txtID10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID10ActionPerformed

    private void txtRFC3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFC3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFC3KeyTyped

    private void txtID11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID11ActionPerformed
    public void limpiar()
    {
        /*txtID.setText("");
        txtNom.setText("");
        txtRFC.setText("");
        txtCALLE.setText("");
        txtNI.setText("");
        txtNEX.setText("");
        txtEstado.setText("");
        txtMunicipio1.setText("");
        txtCOL.setText("");
        txtCP.setText("");
        txtTel.setText("");
        txtemail.setText("");*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPCB;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPAdd;
    private javax.swing.JPanel jPBuscar;
    private javax.swing.JPanel jPDelete;
    private javax.swing.JPanel jPEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblmsgwarning;
    private javax.swing.JPanel pnl_limpar;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtID10;
    private javax.swing.JTextField txtID11;
    private javax.swing.JTextField txtID2;
    private javax.swing.JTextField txtID3;
    private javax.swing.JTextField txtID4;
    private javax.swing.JTextField txtID5;
    private javax.swing.JTextField txtID6;
    private javax.swing.JTextField txtID7;
    private javax.swing.JTextField txtID8;
    private javax.swing.JTextField txtID9;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtRFC1;
    private javax.swing.JTextField txtRFC2;
    private javax.swing.JTextField txtRFC3;
    private javax.swing.JTextField txtTel3;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
