/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Historico_PROV;

import ConexionBD.Conexion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mike
 */
public class HPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form HPrincipal
     */
    DefaultTableModel dtm=new DefaultTableModel();
    int suma=0;
    public HPrincipal() throws SQLException {
        initComponents();
       // suma();

        String[] Titulos=new String []{"NOMBRE DE LA FACTURA ","FECHA INICIO","FECHA FIN","Numero Proveedor","Nombre Proveedor","Importe"};
        dtm.setColumnIdentifiers(Titulos);
        Jt1.setModel(dtm);   
        ct(2);
        
                jsum.setText(Integer.toString(suma()));
    }
    public int suma()
    {
    suma=0;
    int cont=Jt1.getRowCount();
    for(int  i=0;i<cont;i++)
    {
        
        suma+=Integer.parseInt(Jt1.getValueAt(i,5).toString());
        System.out.println(suma);
    }
    return suma;
    }
        private void ct(int valor) throws SQLException 
    {

        java.sql.Statement stm=Conexion.getConexion().createStatement();
        ResultSet rst=stm.executeQuery("select NumFactura, FEmision, FPago, NProveedor,NomProveedor,Importe from CXP where  Estado='"+valor+"' ;");
        while(rst.next())
        {
            dtm.addRow(new Object[]{
            rst.getString(1),
            rst.getDate(2),
            rst.getDate(3),
            rst.getString(4),
            rst.getString(5),
            rst.getInt(6),
   
            });
            
        } 
    }
        private void ct1(Date valor) throws SQLException 
    {

        java.sql.Statement stm=Conexion.getConexion().createStatement();
        ResultSet rst=stm.executeQuery("select * from CXP where FEmision='"+valor+"';");
        while(rst.next())
        {
            dtm.addRow(new Object[]{
            rst.getString(1),
            rst.getDate(2),
            rst.getDate(3),
            rst.getString(4),
            rst.getString(5),
            rst.getInt(6),
   
            });
            
        }    
    
    
    }
        private void limpiar()
        {
        dtm.getDataVector().removeAllElements();
        Jt1.updateUI();
        suma=0;
        }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jt1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jsum = new javax.swing.JTextField();
        pnl_limpar = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        pnl_limpar1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        pnl_limpar2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        pnl_limpar3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        pnl_limpar4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        pnl_limpar5 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(950, 750));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 750));

        jLabel1.setBackground(new java.awt.Color(6, 187, 233));
        jLabel1.setFont(new java.awt.Font("Antique Olive", 1, 24)); // NOI18N
        jLabel1.setText("    HISTORICO DE FACTURAS");

        jPanel2.setBackground(new java.awt.Color(140, 140, 140));

        Jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Jt1);
        if (Jt1.getColumnModel().getColumnCount() > 0) {
            Jt1.getColumnModel().getColumn(0).setResizable(false);
            Jt1.getColumnModel().getColumn(1).setResizable(false);
            Jt1.getColumnModel().getColumn(2).setResizable(false);
            Jt1.getColumnModel().getColumn(3).setResizable(false);
            Jt1.getColumnModel().getColumn(4).setResizable(false);
            Jt1.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(107, 190, 249));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jsum.setEditable(false);
        jPanel5.add(jsum, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 170, -1));

        pnl_limpar.setBackground(new java.awt.Color(107, 190, 249));
        pnl_limpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_limparMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_limparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_limparMouseExited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-escoba-50.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnl_limparLayout = new javax.swing.GroupLayout(pnl_limpar);
        pnl_limpar.setLayout(pnl_limparLayout);
        pnl_limparLayout.setHorizontalGroup(
            pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limparLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl_limparLayout.setVerticalGroup(
            pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limparLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel5.add(pnl_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 100, 50));

        jLabel24.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel24.setText("SALDO TOTAL DE:");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        jLabel25.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel25.setText("VENCIDAS");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        pnl_limpar1.setBackground(new java.awt.Color(107, 190, 249));
        pnl_limpar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_limpar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_limpar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_limpar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_limpar1MouseExited(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-reloj-arena-abajo-50.png"))); // NOI18N
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnl_limpar1Layout = new javax.swing.GroupLayout(pnl_limpar1);
        pnl_limpar1.setLayout(pnl_limpar1Layout);
        pnl_limpar1Layout.setHorizontalGroup(
            pnl_limpar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pnl_limpar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limpar1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel23)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl_limpar1Layout.setVerticalGroup(
            pnl_limpar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnl_limpar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limpar1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel23)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel5.add(pnl_limpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        pnl_limpar2.setBackground(new java.awt.Color(107, 190, 249));
        pnl_limpar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_limpar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_limpar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_limpar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_limpar2MouseExited(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-cancelar2-50.png"))); // NOI18N
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnl_limpar2Layout = new javax.swing.GroupLayout(pnl_limpar2);
        pnl_limpar2.setLayout(pnl_limpar2Layout);
        pnl_limpar2Layout.setHorizontalGroup(
            pnl_limpar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pnl_limpar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limpar2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel26)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl_limpar2Layout.setVerticalGroup(
            pnl_limpar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnl_limpar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limpar2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel26)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel5.add(pnl_limpar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 100, 50));

        jLabel27.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel27.setText("CANCELADAS");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        pnl_limpar3.setBackground(new java.awt.Color(107, 190, 249));
        pnl_limpar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_limpar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_limpar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_limpar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_limpar3MouseExited(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-reloj-de-arena-50.png"))); // NOI18N
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnl_limpar3Layout = new javax.swing.GroupLayout(pnl_limpar3);
        pnl_limpar3.setLayout(pnl_limpar3Layout);
        pnl_limpar3Layout.setHorizontalGroup(
            pnl_limpar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pnl_limpar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limpar3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel28)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl_limpar3Layout.setVerticalGroup(
            pnl_limpar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnl_limpar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limpar3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel28)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel5.add(pnl_limpar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 100, 50));

        jLabel29.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel29.setText("PENDIENTES ");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        pnl_limpar4.setBackground(new java.awt.Color(107, 190, 249));
        pnl_limpar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_limpar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_limpar4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_limpar4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_limpar4MouseExited(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-orden-de-compra-50.png"))); // NOI18N
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnl_limpar4Layout = new javax.swing.GroupLayout(pnl_limpar4);
        pnl_limpar4.setLayout(pnl_limpar4Layout);
        pnl_limpar4Layout.setHorizontalGroup(
            pnl_limpar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_limpar4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(22, 22, 22))
        );
        pnl_limpar4Layout.setVerticalGroup(
            pnl_limpar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_limpar4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel30))
        );

        jPanel5.add(pnl_limpar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 100, 50));

        jLabel31.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel31.setText("PAGADAS");
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        pnl_limpar5.setBackground(new java.awt.Color(107, 190, 249));
        pnl_limpar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_limpar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_limpar5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_limpar5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_limpar5MouseExited(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-calendario-10-50.png"))); // NOI18N
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnl_limpar5Layout = new javax.swing.GroupLayout(pnl_limpar5);
        pnl_limpar5.setLayout(pnl_limpar5Layout);
        pnl_limpar5Layout.setHorizontalGroup(
            pnl_limpar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pnl_limpar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limpar5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel32)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl_limpar5Layout.setVerticalGroup(
            pnl_limpar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnl_limpar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limpar5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel32)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel5.add(pnl_limpar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 50));

        jLabel33.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel33.setText("BUSCAR POR FECHA");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel34.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel34.setText("LIMPIAR FORMULARIO");
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limparMouseClicked
        limpiar();
    }//GEN-LAST:event_pnl_limparMouseClicked

    private void pnl_limparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limparMouseEntered
        pnl_limpar.setBackground(Color.red);
    }//GEN-LAST:event_pnl_limparMouseEntered

    private void pnl_limparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limparMouseExited
        pnl_limpar.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_pnl_limparMouseExited

    private void pnl_limpar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar1MouseClicked
        limpiar();
        try {       
            ct(0);
        } catch (SQLException ex) {
            Logger.getLogger(HPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jsum.setText(Integer.toString(suma()));
    }//GEN-LAST:event_pnl_limpar1MouseClicked

    private void pnl_limpar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar1MouseEntered
       pnl_limpar1.setBackground(Color.red);
    }//GEN-LAST:event_pnl_limpar1MouseEntered

    private void pnl_limpar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar1MouseExited
        pnl_limpar1.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_pnl_limpar1MouseExited

    private void pnl_limpar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar2MouseClicked
        
        limpiar();
        try {       
            ct(3);
        } catch (SQLException ex) {
            Logger.getLogger(HPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jsum.setText(Integer.toString(suma()));
    }//GEN-LAST:event_pnl_limpar2MouseClicked

    private void pnl_limpar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar2MouseEntered
     pnl_limpar2.setBackground(Color.red);
    }//GEN-LAST:event_pnl_limpar2MouseEntered

    private void pnl_limpar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar2MouseExited
        pnl_limpar2.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_pnl_limpar2MouseExited

    private void pnl_limpar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar3MouseClicked
        limpiar();
        try {       
            ct(2);
        } catch (SQLException ex) {
            Logger.getLogger(HPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jsum.setText(Integer.toString(suma()));
    }//GEN-LAST:event_pnl_limpar3MouseClicked

    private void pnl_limpar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar3MouseEntered
    pnl_limpar3.setBackground(Color.red);
    }//GEN-LAST:event_pnl_limpar3MouseEntered

    private void pnl_limpar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar3MouseExited
        pnl_limpar3.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_pnl_limpar3MouseExited

    private void pnl_limpar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar4MouseClicked
        limpiar();
        try {       
            ct(1);
        } catch (SQLException ex) {
            Logger.getLogger(HPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jsum.setText(Integer.toString(suma()));
    }//GEN-LAST:event_pnl_limpar4MouseClicked

    private void pnl_limpar4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar4MouseEntered
    pnl_limpar4.setBackground(Color.red);
    }//GEN-LAST:event_pnl_limpar4MouseEntered

    private void pnl_limpar4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar4MouseExited
       pnl_limpar4.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_pnl_limpar4MouseExited

    private void pnl_limpar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar5MouseClicked
   Date date = null ;
        String i;
    i=JOptionPane.showInputDialog("Ingrese la fecha (mes-dia-anio):");
    //String dma;
    //dma=JOptionPane.showInputDialog("Ingrese el dia:");
    /*while(cal[i]!='\0' || i>=0)
    {
        for(int j=0;j<=7;j++)
        {
                if (cal[j] > 47 && cal[j] < 58) //uso de codigo ASCII 
                {
                    i++; // cuenta solo cuando se elegi un numero 
                    f[j]=cal[j];
                }
                else
                {
                   i=-1;
                   j=7;
                }
        }
    }
    if(i>=7)
    {*/
    //    cal2=f.toString();
    //    cal1=Integer.parseInt(cal2);
        System.out.println(i);
        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
        try {
            date= formato.parse(i);
        } catch (ParseException ex) {
            Logger.getLogger(HPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiar();
        try {       
            ct1(date);
        } catch (SQLException ex) {
            Logger.getLogger(HPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jsum.setText(Integer.toString(suma()));
   // }
  /*  else
    {
        JOptionPane.showMessageDialog(null,"Usted ha ingresado un valor equivocado, intentelo de nuevo");
    }*/
    
    }//GEN-LAST:event_pnl_limpar5MouseClicked

    private void pnl_limpar5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar5MouseEntered
    pnl_limpar5.setBackground(Color.red);
    }//GEN-LAST:event_pnl_limpar5MouseEntered

    private void pnl_limpar5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limpar5MouseExited
        pnl_limpar5.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_pnl_limpar5MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jt1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jsum;
    private javax.swing.JPanel pnl_limpar;
    private javax.swing.JPanel pnl_limpar1;
    private javax.swing.JPanel pnl_limpar2;
    private javax.swing.JPanel pnl_limpar3;
    private javax.swing.JPanel pnl_limpar4;
    private javax.swing.JPanel pnl_limpar5;
    // End of variables declaration//GEN-END:variables
}
