/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Historico_PROV;

import ConexionBD.Conexion;
import com.sun.jdi.connect.spi.Connection;
import java.beans.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Proveedores.Vista;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.table.JTableHeader;
import Proveedores.*;
import cxp.Panel_CXP_Edit1;
/**
 *
 * @author Johan Mendoza
 */
public class THistorico extends javax.swing.JFrame {

    /**
     * Creates new form TablaGeneral_1
     */
    static String usuario;
    int xMouse, yMouse;
    String SIT="";
    int p,dif;
    DefaultTableModel dtm=new DefaultTableModel();
    public THistorico(String usuario) throws SQLException {
        initComponents();
        this.usuario=usuario;
        String[] Titulos=new String []{"NUMERO DE FACTURA","PROVEEDOR","NOMBRE DE PROYECTO","IMPORTE","FECHA INICIO","FECHA FIN","ANTICIPO","COND DE PAGO","ESTADO"};
        dtm.setColumnIdentifiers(Titulos);
        jDatos.setModel(dtm);
        ct();
        this.setLocationRelativeTo(null);
    }
    private void ct() throws SQLException 
    {

        java.sql.Statement stm=Conexion.getConexion().createStatement();
        ResultSet rst=stm.executeQuery("select "
                + "NumFactura, "
                + "NomProveedor, "
                + "NombreProj,"
                + "Importe,"
                + "FEmision,"
                + "FPago,"
                + "Anticipo,"
                + "CondPago,"
                + "Estado from CXP");
        while(rst.next())
        {
            p=rst.getInt(9);
            System.out.println(p);
            //Panel_CXP_Edit1 pcp= new Panel_CXP_Edit1(usuario);
            //pcp.valorpago(p);

            if(p==2) //pendiente 
            {
                SIT="PENDIENTE";
            }
            if(p==1) //pagado
            {
                SIT="PAGADO";
            }
            if(p==0) //cancelado 
            { 
                SIT="CANCELADA";
            }
            
            dtm.addRow(new Object[]{
            rst.getString(1),
            rst.getString(2),
            rst.getString(3),
            rst.getString(4),
            rst.getDate(5),
            rst.getDate(6),
            rst.getFloat(7),
            rst.getInt(8),
            SIT
            });
            
        }   
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnclose = new javax.swing.JButton();
        jbtnclose2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(107, 190, 249));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(140, 140, 140));
        jPanel2.setForeground(new java.awt.Color(6, 187, 233));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(6, 187, 233));
        jLabel1.setFont(new java.awt.Font("Antique Olive", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pantalla de Control de cuentas por pagar");

        jbtnclose.setBackground(new java.awt.Color(0, 0, 0));
        jbtnclose.setFont(new java.awt.Font("Rockwell Condensed", 0, 14)); // NOI18N
        jbtnclose.setForeground(new java.awt.Color(255, 255, 255));
        jbtnclose.setText("X");
        jbtnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtncloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtncloseMousePressed(evt);
            }
        });
        jbtnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncloseActionPerformed(evt);
            }
        });

        jbtnclose2.setBackground(new java.awt.Color(0, 0, 0));
        jbtnclose2.setFont(new java.awt.Font("Rockwell Condensed", 0, 14)); // NOI18N
        jbtnclose2.setForeground(new java.awt.Color(255, 255, 255));
        jbtnclose2.setText("-");
        jbtnclose2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnclose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnclose2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnclose2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnclose2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnclose2MousePressed(evt);
            }
        });
        jbtnclose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclose2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 764, Short.MAX_VALUE)
                .addComponent(jbtnclose2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(159, 159, 159))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnclose2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 70));

        jDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jDatos.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "-", "-", "-"
            }
        ));
        jDatos.setGridColor(new java.awt.Color(0, 0, 0));
        jDatos.setSelectionBackground(new java.awt.Color(107, 190, 249));
        jDatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jDatos.setShowGrid(false);
        jDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 880, 465));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtncloseMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jbtncloseMouseClicked

    private void jbtncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtncloseMouseEntered
        jbtnclose.setBackground(Color.red);
    }//GEN-LAST:event_jbtncloseMouseEntered

    private void jbtncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtncloseMouseExited
        jbtnclose.setBackground(Color.black);
    }//GEN-LAST:event_jbtncloseMouseExited

    private void jbtncloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtncloseMousePressed

    }//GEN-LAST:event_jbtncloseMousePressed

    private void jbtncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtncloseActionPerformed

    private void jbtnclose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnclose2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnclose2MouseClicked

    private void jbtnclose2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnclose2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnclose2MouseEntered

    private void jbtnclose2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnclose2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnclose2MouseExited

    private void jbtnclose2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnclose2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnclose2MousePressed

    private void jbtnclose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclose2ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jbtnclose2ActionPerformed

    private void jDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDatosMouseClicked

        Variables var= new Variables();
        int fs=jDatos.getSelectedRow();
        if(fs>=0)
        {//obtencion mediante un objeto
            String obj[]= new String[3];
            obj[1]=jDatos.getValueAt(fs, 0).toString();
            var.setGetTexto(obj[1]);
            /*sacar(obj[1]);
            //ingresados a un txt
            a=obj[1];
            c=Integer.parseInt(a);
            JOptionPane.showMessageDialog(null,"dato obtenido ID-"+c);
            var.setIDselected(c);
            JOptionPane.showMessageDialog(null,"dato obtenido ID-"+var.getIDselected());
            */

            Vista V1 = null;
            try {
                V1 = new Vista();
            } catch (SQLException ex) {
                Logger.getLogger(TGeneral.class.getName()).log(Level.SEVERE, null, ex);
            }
            V1.setVisible(true);

        }
    }//GEN-LAST:event_jDatosMouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse= evt.getX();
        yMouse= evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(THistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(THistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(THistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(THistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new THistorico(usuario).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(THistorico.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTable jDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnclose;
    private javax.swing.JButton jbtnclose2;
    // End of variables declaration//GEN-END:variables
}
