/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cxc;

import Proveedores.*;
import Proveedores.*;
import ConexionBD.Conexion;
import com.microsoft.sqlserver.jdbc.SQLServerDataSource;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Johan Mendoza
 */
public class Clientes_Principal extends javax.swing.JPanel {

    /**
     * Creates new form Proveedores_Principal
     */
    static int confirmacion;
    String VALORCLIENTE=""; //Ya sea lo que sea escrito en el txt de busqueda se generara el query 
    String IDCLIENTE;
    String NOMCLIENTE;
    String RFCCLIENTE;
    String NOMCALLECLIENTE;
    String NICLIENTE;
    String NECLIENTE;
    String ESTCLIENTE;
    String MUNCLIENTE;
    String COLCLIENTE;
    String CPCLIENTE;    
    String TELCLIENTE;
    String EMAILCLIENTE, NUMCUENTA, CLAVE, NOMCOMERCIAL;
    InputStream is;
    FileInputStream fis;
    int longitudBytes;
    public Clientes_Principal() {
        initComponents();
        txtsearch.setText("".trim());
        txtID.setVisible(false);
        lbl_id.setVisible(false);
        lblmsgwarning.setVisible(false);
        ImageIcon icon;
                        icon = new ImageIcon("Iconografias/icons8-signo-de-interrogación-50.png");
                        lbl_infoc.setText("Este cliente no tiene constancia");
                        lbl_infoc.setForeground(Color.red);
                        lbl_estatusconstancia.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void AnadirDomicilio() throws SQLException{
        Statement stm=Conexion.getConexion().createStatement();
        ResultSet rs=stm.executeQuery("select top(1)  NumCliente from Clientes order by NumCliente desc");
        if(rs.next()){
             IDCLIENTE=rs.getString(1);
             System.out.println(IDCLIENTE);
             JOptionPane.showMessageDialog(null,"Su identificador es:"+IDCLIENTE);
             rs=stm.executeQuery("insert into DomClientes values('"+Integer.parseInt(IDCLIENTE)+"','"+NOMCALLECLIENTE+"','"+NECLIENTE+"','"+NICLIENTE+"','"+ESTCLIENTE+"','"+MUNCLIENTE+"','"+COLCLIENTE+"','"+CPCLIENTE+"','"+Integer.parseInt(TELCLIENTE.trim())+"','"+EMAILCLIENTE+"')");
        }
    }
    public void AnadirDatosBancarios() throws SQLException{
        Statement stm=Conexion.getConexion().createStatement();
        ResultSet rs=stm.executeQuery("select top(1)  NumCliente from Clientes order by NumCliente desc");
        if(rs.next()){
             IDCLIENTE=rs.getString(1);
             System.out.println(IDCLIENTE);
             JOptionPane.showMessageDialog(null,"Su identificador es:"+IDCLIENTE);
             rs=stm.executeQuery("insert into BancoClientes values('"+Integer.parseInt(IDCLIENTE)+"','"+Integer.parseInt(NUMCUENTA)+"','"+CLAVE+"','"+NOMCOMERCIAL+"')");
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_clave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNEX = new javax.swing.JTextField();
        txtNI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCOL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl_infoc = new javax.swing.JLabel();
        txt_nomcomercial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtCALLE = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        lbl_id1 = new javax.swing.JLabel();
        lbl_id2 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        lbl_id3 = new javax.swing.JLabel();
        txt_numcuenta = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        panel_constancia = new javax.swing.JPanel();
        lbl_estatusconstancia = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPEditar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPAdd = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPDelete = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pnl_limpar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        JPCB = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPBuscar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblmsgwarning = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(950, 550));

        jPanel1.setBackground(new java.awt.Color(140, 140, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("Clave Interbancaria");
        jPanel1.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 160, -1));

        txtID.setEditable(false);
        txtID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, -1));

        txt_clave.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claveActionPerformed(evt);
            }
        });
        jPanel1.add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 160, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Razón Social");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Num Exterior");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 76, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Num interior");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 78, -1));

        txtNEX.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNEX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNEXKeyTyped(evt);
            }
        });
        jPanel1.add(txtNEX, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 76, -1));

        txtNI.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNIKeyTyped(evt);
            }
        });
        jPanel1.add(txtNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 78, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Colonia");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 82, -1));

        txtCOL.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtCOL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Codigo Postal");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 82, -1));

        txtCP.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPKeyTyped(evt);
            }
        });
        jPanel1.add(txtCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre Comercial");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 140, -1));

        lbl_infoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_infoc.setForeground(new java.awt.Color(255, 255, 255));
        lbl_infoc.setText("Constancia de Situación Fiscal");
        jPanel1.add(lbl_infoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 190, 40));

        txt_nomcomercial.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nomcomercial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomcomercialKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nomcomercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 380, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 82, -1));

        txtEstado.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 230, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("E-MAIL");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 82, -1));

        txtemail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 230, -1));

        txtCALLE.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCALLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCALLEActionPerformed(evt);
            }
        });
        jPanel1.add(txtCALLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 120, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Municipio");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 82, -1));

        txtMunicipio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMunicipioActionPerformed(evt);
            }
        });
        txtMunicipio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMunicipioKeyTyped(evt);
            }
        });
        jPanel1.add(txtMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 100, -1));
        jPanel1.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 420, -1));

        lbl_id1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_id1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id1.setText("Código de identificación");
        jPanel1.add(lbl_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        lbl_id2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_id2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id2.setText("Datos Bancarios");
        jPanel1.add(lbl_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 160, 20));

        txtTel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, -1));

        lbl_id3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_id3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id3.setText("Número de Cuenta");
        jPanel1.add(lbl_id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 160, -1));

        txt_numcuenta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_numcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numcuentaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_numcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 160, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("RFC");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 50, -1));

        txtRFC.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFCKeyTyped(evt);
            }
        });
        jPanel1.add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 230, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 110, 100));

        panel_constancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_constanciaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_constanciaLayout = new javax.swing.GroupLayout(panel_constancia);
        panel_constancia.setLayout(panel_constanciaLayout);
        panel_constanciaLayout.setHorizontalGroup(
            panel_constanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_constanciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_estatusconstancia, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_constanciaLayout.setVerticalGroup(
            panel_constanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_constanciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_estatusconstancia, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panel_constancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 110, 100));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Nombre de calle");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 110, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Ver contratos");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 110, -1));

        jPanel5.setBackground(new java.awt.Color(107, 190, 249));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPEditar.setBackground(new java.awt.Color(107, 190, 249));
        jPEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPEditarMouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-editar-50.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPEditarLayout = new javax.swing.GroupLayout(jPEditar);
        jPEditar.setLayout(jPEditarLayout);
        jPEditarLayout.setHorizontalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPEditarLayout.setVerticalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEditarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14))
        );

        jPanel5.add(jPEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        jPAdd.setBackground(new java.awt.Color(107, 190, 249));
        jPAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPAddMouseExited(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-añadir-usuario-masculino-50.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPAddLayout = new javax.swing.GroupLayout(jPAdd);
        jPAdd.setLayout(jPAddLayout);
        jPAddLayout.setHorizontalGroup(
            jPAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAddLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPAddLayout.setVerticalGroup(
            jPAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAddLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.add(jPAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 90, 50));

        jPDelete.setBackground(new java.awt.Color(107, 190, 249));
        jPDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPDeleteMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-borrar-para-siempre-50.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPDeleteLayout = new javax.swing.GroupLayout(jPDelete);
        jPDelete.setLayout(jPDeleteLayout);
        jPDeleteLayout.setHorizontalGroup(
            jPDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDeleteLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(23, 23, 23))
        );
        jPDeleteLayout.setVerticalGroup(
            jPDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDeleteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15))
        );

        jPanel5.add(jPDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 100, 60));

        pnl_limpar.setBackground(new java.awt.Color(107, 190, 249));
        pnl_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_limparMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_limparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_limparMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-escoba-50.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnl_limparLayout = new javax.swing.GroupLayout(pnl_limpar);
        pnl_limpar.setLayout(pnl_limparLayout);
        pnl_limparLayout.setHorizontalGroup(
            pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_limparLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnl_limparLayout.setVerticalGroup(
            pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_limparLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel5.add(pnl_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 100, 50));

        jPanel6.setBackground(new java.awt.Color(107, 190, 249));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-tabla-40.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel17)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 70, 50));

        jLabel20.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel20.setText("EDITAR USUARIO");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel25.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel25.setText("ELIMINAR USUARIO");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, -1));

        jLabel24.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel24.setText("GENERAR NUEVO CLIENTE");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel23.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel23.setText("LIMPIAR FORMULARIO");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jLabel21.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel21.setText("MOSTRAR TABLA GENERAL");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Antique Olive", 1, 24)); // NOI18N
        jLabel18.setText("MENU PRINCIPAL DE CLIENTES");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPCB.setBackground(new java.awt.Color(140, 140, 140));

        jPanel4.setBackground(new java.awt.Color(140, 140, 140));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jPBuscar.setBackground(new java.awt.Color(140, 140, 140));
        jPBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPBuscarMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-búsqueda-50 (1).png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPBuscarLayout = new javax.swing.GroupLayout(jPBuscar);
        jPBuscar.setLayout(jPBuscarLayout);
        jPBuscarLayout.setHorizontalGroup(
            jPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBuscarLayout.setVerticalGroup(
            jPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        lblmsgwarning.setFont(new java.awt.Font("Rockwell", 3, 12)); // NOI18N
        lblmsgwarning.setForeground(new java.awt.Color(255, 0, 51));
        lblmsgwarning.setText("¡DEBES COLOCAR INFORMACIÓN PARA GENERAR UNA BUSQUEDA!");

        javax.swing.GroupLayout JPCBLayout = new javax.swing.GroupLayout(JPCB);
        JPCB.setLayout(JPCBLayout);
        JPCBLayout.setHorizontalGroup(
            JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPCBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmsgwarning)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPCBLayout.setVerticalGroup(
            JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPCBLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JPCBLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(JPCBLayout.createSequentialGroup()
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblmsgwarning))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPCB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCALLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCALLEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCALLEActionPerformed

    private void txtMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMunicipioActionPerformed

    private void jPEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEditarMouseClicked
        // Editar la informacion 
                IDCLIENTE=txtID.getText();
                NOMCLIENTE=txtNom.getText();
                RFCCLIENTE=txtRFC.getText();
                NOMCALLECLIENTE=txtCALLE.getText();
                NICLIENTE=txtNI.getText();
                NECLIENTE=txtNEX.getText();
                ESTCLIENTE=txtEstado.getText();
                MUNCLIENTE=txtMunicipio.getText();
                COLCLIENTE=txtCOL.getText();
                CPCLIENTE=txtCP.getText();
                TELCLIENTE=txtTel.getText();
                EMAILCLIENTE=txtemail.getText();
                NUMCUENTA = txt_numcuenta.getText();
                CLAVE = txt_clave.getText();
                NOMCOMERCIAL = txt_nomcomercial.getText();
                
        try{                
        confirmacion=JOptionPane.showConfirmDialog(null,"Usted ha ingresado los siguientes datos en el ID:"+IDCLIENTE
                +"\nNombre del proveedor:"+NOMCLIENTE
                +"\nRFC:"+RFCCLIENTE
                +"\nCalle:"+NOMCALLECLIENTE
                +"\nNumero interior:"+NICLIENTE
                +"\nNumero exterior:"+NECLIENTE
                +"\nEstado:"+ESTCLIENTE
                +"\nMunicipio:"+MUNCLIENTE
                +"\nColonia:"+COLCLIENTE
                +"\nCodigo Postal:"+COLCLIENTE
                +"\nTelefono:"+TELCLIENTE
                +"\nCorreo electronico:"+EMAILCLIENTE
                +"\nNombre Comercial:"+NOMCOMERCIAL
                +"\nDATOS BANCARIOS:"
                +"\nNumero de Cuenta:"+NUMCUENTA
                +"\nClave Interbancaria:"+CLAVE
                +"\n¿Desea aceptar la modificacion en los datos?");
        if(confirmacion==0)
        {

            Statement stm=Conexion.getConexion().createStatement();     
            ResultSet rs=stm.executeQuery("select NumCliente"
                    + ",NomCliente, "
                    + "RFC, "
                    + "Constancia,"
                    + "Nombre_Calle, "
                    + "Num_Int, "
                    + "Num_Ext, "
                    + "Estado, "
                    + "Municipio, "
                    + "Colonia, "
                    + "CP, "
                    + "Telefono, "   
                    + "Email "
                    + "FROM Clientes inner join DomClientes on Clientes.NumCliente=DomClientes.Num_Cliente "
                    + "where RFC like '%"+RFCCLIENTE+"%' or NomCliente like '%"+NOMCLIENTE+"%'");            
            if(rs.next())
            {
                try{
            String sql="UPDATE Clientes set NomCliente = ?, RFC = ?, Constancia = ? where NumCliente ="+IDCLIENTE;

            PreparedStatement ps=Conexion.getConexion().prepareStatement(sql);
            //ps.setInt(1,Integer.parseInt(txtcodigo.getText()));
            ps.setString(1,NOMCLIENTE);
            ps.setString(2, RFCCLIENTE);
            ps.setBinaryStream(3,fis,longitudBytes);
            ps.execute();
            ps.close();
            rs = stm.executeQuery("Update BancoClientes set NumCuenta ='"+Integer.parseInt(NUMCUENTA)+"', Clave = '"+CLAVE+"', NombreComercial='"+NOMCOMERCIAL+"' where NumCliente='"+IDCLIENTE+"'");
            
            JOptionPane.showMessageDialog(null,"Guardado correctamente");
        }catch(SQLException | NumberFormatException | HeadlessException x){
            JOptionPane.showMessageDialog(null, "exception 2 "+x);
        }
            
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Sus datos no pueden ser modificados");
             //rs=stm.executeQuery("Update Clientes set NomCliente='"+NOMCLIENTE+"',RFC='"+RFCCLIENTE+"' where  NumCliente='"+IDCLIENTE+"'"); 
            
             //JOptionPane.showMessageDialog(null,"Datos editados correctamente!");
             
            }    
             
        

        }
        }catch(SQLException ex) {
            Logger.getLogger(Clientes_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_jPEditarMouseClicked

    private void txt_nomcomercialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomcomercialKeyTyped
       
    }//GEN-LAST:event_txt_nomcomercialKeyTyped

    private void txtCPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPKeyTyped
        if(txtCP.getText().length() >= 5)
        {
        evt.consume();
        }       
    }//GEN-LAST:event_txtCPKeyTyped

    private void txtNEXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNEXKeyTyped
        if(txtNEX.getText().length() >= 3)
        {
        evt.consume();
        }        
    }//GEN-LAST:event_txtNEXKeyTyped

    private void txtNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIKeyTyped
        if(txtNI.getText().length() >= 3)
        {
        evt.consume();
        }
    }//GEN-LAST:event_txtNIKeyTyped

    private void txtMunicipioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMunicipioKeyTyped
        if(txtMunicipio.getText().length() >= 15)
        {
        evt.consume();
        }
    }//GEN-LAST:event_txtMunicipioKeyTyped

    private void jPDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDeleteMouseClicked
        // Eleminacion de un proveedor  
        
        
        
    }//GEN-LAST:event_jPDeleteMouseClicked

    private void jPAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAddMouseClicked
        //prueba con boton 
                NOMCLIENTE=txtNom.getText();
                RFCCLIENTE=txtRFC.getText();
                NOMCALLECLIENTE=txtCALLE.getText();
                NICLIENTE=txtNI.getText();
                NECLIENTE=txtNEX.getText();
                ESTCLIENTE=txtEstado.getText();
                MUNCLIENTE=txtMunicipio.getText();
                COLCLIENTE=txtCOL.getText();
                CPCLIENTE=txtCP.getText();
                TELCLIENTE=txtTel.getText();
                EMAILCLIENTE=txtemail.getText();
                NUMCUENTA = txt_numcuenta.getText();
                CLAVE = txt_clave.getText();
                NOMCOMERCIAL = txt_nomcomercial.getText();
             try 
        {
            
            Statement stm=Conexion.getConexion().createStatement();
            ResultSet rs=stm.executeQuery("select * from Clientes where RFC like '%"+RFCCLIENTE+"%' or NomCliente ='"+NOMCLIENTE+"'");  
         if (rs.next()==false)
          {
             String sql="INSERT INTO Clientes (NomCliente, RFC, Constancia) VALUES (?, ?, ?)";

             PreparedStatement ps=Conexion.getConexion().prepareStatement(sql);
            //ps.setInt(1,Integer.parseInt(txtcodigo.getText()));
            ps.setString(1,NOMCLIENTE);
            ps.setString(2,RFCCLIENTE);
            ps.setBinaryStream(3,fis,longitudBytes);
            ps.execute();
            ps.close();

             
             JOptionPane.showMessageDialog(null,"Su operación exitosa!");
          }
         else 
         {
           JOptionPane.showMessageDialog(null,"Su operación no puede realizarse!");
         }
            
                  
            
        } catch (SQLException ex) {
            Logger.getLogger(Clientes_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }   
        try {
            AnadirDomicilio();
        } catch (SQLException ex) {
            Logger.getLogger(Clientes_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            AnadirDatosBancarios();
        } catch (SQLException ex) {
            Logger.getLogger(Clientes_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }//GEN-LAST:event_jPAddMouseClicked

    private void pnl_limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limparMouseClicked
        // TODO add your handling code here:
        txtID.setText("");
        txtNom.setText("");
        txt_nomcomercial.setText("");
        txtCALLE.setText("");
        txtNI.setText("");
        txtNEX.setText("");
        txtEstado.setText("");
        txtMunicipio.setText("");
        txtCOL.setText("");
        txtCP.setText("");
        txt_clave.setText("");
        txtemail.setText("");
        txtID.setVisible(false);
        lbl_id.setVisible(false);
    }//GEN-LAST:event_pnl_limparMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        try {
            // TODO add your handling code here:

            TGeneral tg = new TGeneral();
            tg.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Clientes_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void txt_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claveActionPerformed

    private void jPEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEditarMouseEntered
     jPEditar.setBackground(Color.red);
    }//GEN-LAST:event_jPEditarMouseEntered

    private void jPEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEditarMouseExited
     jPEditar.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_jPEditarMouseExited

    private void jPDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDeleteMouseEntered
    jPDelete.setBackground(Color.red);
    }//GEN-LAST:event_jPDeleteMouseEntered

    private void jPDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDeleteMouseExited
    jPDelete.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_jPDeleteMouseExited

    private void jPAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAddMouseEntered
    jPAdd.setBackground(Color.red);
    }//GEN-LAST:event_jPAddMouseEntered

    private void jPAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAddMouseExited
    jPAdd.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_jPAddMouseExited

    private void pnl_limparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limparMouseEntered
    pnl_limpar.setBackground(Color.red);
    }//GEN-LAST:event_pnl_limparMouseEntered

    private void pnl_limparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limparMouseExited
    pnl_limpar.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_pnl_limparMouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
    jPanel6.setBackground(Color.red);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
    jPanel6.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBuscarMouseExited
        jPBuscar.setBackground(new java.awt.Color(140,140,140));
    }//GEN-LAST:event_jPBuscarMouseExited

    private void jPBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBuscarMouseEntered
        jPBuscar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPBuscarMouseEntered

    private void jPBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBuscarMouseClicked
        // Aqui es donde se generara la busqueda
        ImageIcon foto;
        VALORCLIENTE=txtsearch.getText();
        lbl_estatusconstancia.setIcon(null);
        if(VALORCLIENTE.isEmpty())
        //if(txtsearch.getText().isEmpity())
        {
            txtID.setText(" ");
            txtNom.setText(" ");
            txt_nomcomercial.setText(" ");
            txtCALLE.setText(" ");
            txtNI.setText(" ");
            txtNEX.setText(" ");
            txtEstado.setText(" ");
            txtMunicipio.setText(" ");
            txtCOL.setText(" ");
            txtCP.setText(" ");
            txt_clave.setText(" ");
            txtemail.setText(" ");
            lblmsgwarning.setVisible(true);


        }
        else 
        {
            lblmsgwarning.setVisible(false);

            txtID.setVisible(true);
            lbl_id.setVisible(true);
            SQLServerDataSource con = new SQLServerDataSource();
            con.setServerName("localhost");
            con.setDatabaseName("Gestion4F");
            con.setUser("4FAdmin"); //CAMBIO
            con.setPassword("CuatroF");
            con.setPortNumber(1433);
            
            String url = "select * FROM Clientes inner join DomClientes on Clientes.NumCliente=DomClientes.Num_Cliente where NumCliente ="+txtsearch.getText();
            /*String url = "select NumCliente"
            + ",NomCliente, "
            + "RFC, "
            + "Constancia,"
            + "Nombre_Calle, "
            + "Num_Int, "
            + "Num_Ext, "
            + "Estado, "
            + "Municipio, "
            + "Colonia, "
            + "CP, "
            + "Telefono, "
            + "Email "
            + "FROM Clientes inner join DomClientes on Clientes.NumCliente=DomClientes.Num_Cliente "
            + "where NumCliente ="+txtsearch.getText(); //like '%"+VALORCLIENTE+"%'";*/
            try {
                Connection cn = con.getConnection();
                PreparedStatement ps = cn.prepareStatement(url);
                ResultSet rst = ps.executeQuery();

                while(rst.next())
                {
                    IDCLIENTE=rst.getString(1);
                    NOMCLIENTE=rst.getString(2);
                    RFCCLIENTE=rst.getString(3);
                   NOMCALLECLIENTE=rst.getString(5);
                    NICLIENTE=rst.getString(6);
                    NECLIENTE=rst.getString(7);
                    ESTCLIENTE=rst.getString(8);
                    MUNCLIENTE=rst.getString(9);
                    COLCLIENTE=rst.getString(10);
                    CPCLIENTE =rst.getString(11);
                    TELCLIENTE=rst.getString(12);
                    EMAILCLIENTE=rst.getString(13);
                    is = rst.getBinaryStream(4);
                    

                    txtID.setText(IDCLIENTE.trim());
                    txtNom.setText(NOMCLIENTE.trim());
                    txtRFC.setText(RFCCLIENTE.trim());
                    txtCALLE.setText(NOMCALLECLIENTE.trim());
                    txtNI.setText(NICLIENTE.trim());
                    txtNEX.setText(NECLIENTE.trim());
                    txtEstado.setText(ESTCLIENTE.trim());
                    txtMunicipio.setText(MUNCLIENTE.trim());
                    txtCOL.setText(COLCLIENTE.trim());
                    txtCP.setText(CPCLIENTE.trim());
                    txtTel.setText(TELCLIENTE.trim());
                    txtemail.setText(EMAILCLIENTE.trim());
                    
                   if(is != null){
                        BufferedImage bi = ImageIO.read(is);
                         foto = new ImageIcon(bi);
                         System.out.println(bi);
                         Image img = foto.getImage();
                         Image newimg = img.getScaledInstance(140, 170, java.awt.Image.SCALE_SMOOTH);
                
                         ImageIcon newicon = new ImageIcon(newimg);
                
                         lbl_estatusconstancia.setIcon(newicon);
 
                        lbl_infoc.setText("Ver Constancia");
                        lbl_infoc.setForeground(Color.green);
                    } else {
                        ImageIcon icon;
                        icon = new ImageIcon("Iconografias/icons8-signo-de-interrogación-50.png");
                       lbl_infoc.setText("Este cliente no tiene constancia");
                        lbl_infoc.setForeground(Color.red);
                       lbl_infoc.setIcon(icon);
                    }

                }

            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null,"exception: "+ex);
               //System.out.print(ex);
            }
        }
    }//GEN-LAST:event_jPBuscarMouseClicked

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txt_numcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numcuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numcuentaActionPerformed

    private void txtRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCKeyTyped
        // TODO add your handling code here:
         if(txtRFC.getText().length() >= 13)
        {
        evt.consume();
        }
    }//GEN-LAST:event_txtRFCKeyTyped

    private void panel_constanciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_constanciaMouseClicked
        // TODO add your handling code here:
        try{
        if(is == null){
                     lbl_estatusconstancia.setIcon(null);
                     JFileChooser j=new JFileChooser();
                     j.setFileSelectionMode(JFileChooser.FILES_ONLY);//solo archivos y no carpetas
                     int estado=j.showOpenDialog(null);
                     if(estado== JFileChooser.APPROVE_OPTION){
            try{
                    fis=new FileInputStream(j.getSelectedFile());
                    //necesitamos saber la cantidad de bytes
                    this.longitudBytes=(int)j.getSelectedFile().length();
                    try {
                    Image icono=ImageIO.read(j.getSelectedFile()).getScaledInstance
                        (lbl_estatusconstancia.getWidth(),lbl_estatusconstancia.getHeight(),Image.SCALE_DEFAULT);
                    lbl_estatusconstancia.setIcon(new ImageIcon(icono));
                    lbl_estatusconstancia.updateUI();

                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "imagen: "+ex);
               }
            }catch(FileNotFoundException ex){
                ex.printStackTrace();
            }
        }
                    } else {
                        ImageIcon icon;
                        icon = new ImageIcon("Iconografias/icons8-marca-de-verificación-50.png");
                        lbl_infoc.setText("VER CONSTANCIA");
                        lbl_infoc.setForeground(Color.green);
                        lbl_estatusconstancia.setIcon(icon);
                    }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"exception: "+ex);
        }
    }//GEN-LAST:event_panel_constanciaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPAdd;
    private javax.swing.JPanel jPBuscar;
    private javax.swing.JPanel jPDelete;
    private javax.swing.JPanel jPEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_estatusconstancia;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_id1;
    private javax.swing.JLabel lbl_id2;
    private javax.swing.JLabel lbl_id3;
    private javax.swing.JLabel lbl_infoc;
    private javax.swing.JLabel lblmsgwarning;
    private javax.swing.JPanel panel_constancia;
    private javax.swing.JPanel pnl_limpar;
    private javax.swing.JTextField txtCALLE;
    private javax.swing.JTextField txtCOL;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNEX;
    private javax.swing.JTextField txtNI;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txt_clave;
    private javax.swing.JTextField txt_nomcomercial;
    private javax.swing.JTextField txt_numcuenta;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
