/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cxc;

import cxp.*;
import ConexionBD.Conexion;
import Proveedores.Proveedores_Principal;
import Proveedores.TGeneral;
import com.microsoft.sqlserver.jdbc.SQLServerDataSource;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Johan Mendoza
 */
public class Panel_CXC_Edit extends javax.swing.JPanel {

    String numfact;
    static int NumCliente, confirmacion, Estatus, condpago;
    static double importetotal, anticipo, saldoxcobrar;
    static Date date, datesum;
    static String NombreCliente, NombreProyecto, NumFacturaAnterior, NumFactura, Solicitante, Concepto;
    /**
     * Creates new form Panel_CXP
     */
    public Panel_CXC_Edit() {
        initComponents();
    }
    
    public static String sumarDiasAFecha(String fecha, int dias) {
    if(dias == 0){
        return fecha;
    }

    String[] f = fecha.split("-");
    Calendar calendar = Calendar.getInstance();
    //calendar.setTime(new Date(Integer.parseInt(f[0]), Integer.parseInt(f[1]), Integer.parseInt(f[2])));
    calendar.set(Integer.parseInt(f[0]), Integer.parseInt(f[1])-1, Integer.parseInt(f[2]));

    calendar.add(Calendar.DAY_OF_MONTH, dias);
    SimpleDateFormat fe = new SimpleDateFormat("YYYY-MM-dd");
    return fe.format(calendar.getTime());

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCondPago = new javax.swing.ButtonGroup();
        btnGroupAnticipo = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtsearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPBuscar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nombreproyecto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_concepto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_NCliente = new javax.swing.JLabel();
        lbl_fpago = new javax.swing.JLabel();
        txt_numfactura = new javax.swing.JTextField();
        txt_nomsolicitante = new javax.swing.JTextField();
        jdc_Fechaem = new com.toedter.calendar.JDateChooser();
        jLabel27 = new javax.swing.JLabel();
        txt_numcliente = new javax.swing.JTextField();
        lbl_estatustitulo = new javax.swing.JLabel();
        txt_anticipo = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        lbl_estatus = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chk_cancelado = new javax.swing.JCheckBox();
        txt_total2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        chk_150d = new javax.swing.JCheckBox();
        chk_60d = new javax.swing.JCheckBox();
        chk_90d = new javax.swing.JCheckBox();
        chk_inmediato = new javax.swing.JCheckBox();
        lbl_saldoxcobrar = new javax.swing.JLabel();
        chk_30d = new javax.swing.JCheckBox();
        chk_120d = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jPEditar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPAdd = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPDelete = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pnl_limpar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(950, 550));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Antique Olive", 1, 24)); // NOI18N
        jLabel18.setText("MENU PRINCIPAL DE CUENTAS POR COBRAR");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(140, 140, 140));

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Búsqueda por Número de Factura");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(140, 140, 140));

        jPBuscar.setBackground(new java.awt.Color(140, 140, 140));
        jPBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPBuscarMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/lupa.png"))); // NOI18N

        javax.swing.GroupLayout jPBuscarLayout = new javax.swing.GroupLayout(jPBuscar);
        jPBuscar.setLayout(jPBuscarLayout);
        jPBuscarLayout.setHorizontalGroup(
            jPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBuscarLayout.setVerticalGroup(
            jPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(140, 140, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("Número de Factura");
        jPanel1.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 160, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre del Cliente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de Emisión");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 130, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre del Proyecto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, -1));

        txt_nombreproyecto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nombreproyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreproyectoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nombreproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Condiciones de Pago");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 120, -1));

        txt_concepto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_concepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_conceptoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 480, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Anticipo");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 50, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nombre del Solicitante");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 130, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Concepto");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 80, -1));

        lbl_NCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_NCliente.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl_NCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 20));

        lbl_fpago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_fpago.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl_fpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 20));
        jPanel1.add(txt_numfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, -1));

        txt_nomsolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomsolicitanteActionPerformed(evt);
            }
        });
        txt_nomsolicitante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nomsolicitanteKeyReleased(evt);
            }
        });
        jPanel1.add(txt_nomsolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 280, -1));
        jPanel1.add(jdc_Fechaem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Número de Cliente");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 130, -1));

        txt_numcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numclienteActionPerformed(evt);
            }
        });
        txt_numcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numclienteKeyReleased(evt);
            }
        });
        jPanel1.add(txt_numcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 170, -1));

        lbl_estatustitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_estatustitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_estatustitulo.setText("Estatus");
        jPanel1.add(lbl_estatustitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 80, -1));

        txt_anticipo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_anticipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_anticipoActionPerformed(evt);
            }
        });
        txt_anticipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_anticipoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_anticipoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_anticipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 170, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Importe Total");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 80, -1));

        lbl_estatus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(lbl_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 220, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha Límite/Fecha de Pago");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 210, -1));

        chk_cancelado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_cancelado.setText("Factura Cancelada");
        chk_cancelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_canceladoActionPerformed(evt);
            }
        });
        jPanel1.add(chk_cancelado, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        txt_total2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_total2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total2ActionPerformed(evt);
            }
        });
        txt_total2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_total2KeyTyped(evt);
            }
        });
        jPanel1.add(txt_total2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 170, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Saldo por Cobrar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, -1));

        btnGroupCondPago.add(chk_150d);
        chk_150d.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_150d.setText("150 días");
        chk_150d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_150dActionPerformed(evt);
            }
        });
        jPanel1.add(chk_150d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        btnGroupCondPago.add(chk_60d);
        chk_60d.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_60d.setText("60 días");
        chk_60d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_60dActionPerformed(evt);
            }
        });
        jPanel1.add(chk_60d, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        btnGroupCondPago.add(chk_90d);
        chk_90d.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_90d.setText("90 días");
        chk_90d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_90dActionPerformed(evt);
            }
        });
        jPanel1.add(chk_90d, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        btnGroupCondPago.add(chk_inmediato);
        chk_inmediato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_inmediato.setText("Inmediato");
        chk_inmediato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_inmediatoActionPerformed(evt);
            }
        });
        jPanel1.add(chk_inmediato, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        lbl_saldoxcobrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_saldoxcobrar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_saldoxcobrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lbl_saldoxcobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, 20));

        btnGroupCondPago.add(chk_30d);
        chk_30d.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_30d.setText("30 días");
        chk_30d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_30dActionPerformed(evt);
            }
        });
        jPanel1.add(chk_30d, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        btnGroupCondPago.add(chk_120d);
        chk_120d.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_120d.setText("120 días");
        chk_120d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_120dActionPerformed(evt);
            }
        });
        jPanel1.add(chk_120d, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jPanel5.setBackground(new java.awt.Color(107, 190, 249));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPEditar.setBackground(new java.awt.Color(107, 190, 249));
        jPEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPEditarMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/Lapiz.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPEditarLayout = new javax.swing.GroupLayout(jPEditar);
        jPEditar.setLayout(jPEditarLayout);
        jPEditarLayout.setHorizontalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel14)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPEditarLayout.setVerticalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEditarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14))
        );

        jPanel5.add(jPEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, 90, -1));

        jPAdd.setBackground(new java.awt.Color(107, 190, 249));
        jPAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPAddMouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-recibo-dólar-50.png"))); // NOI18N

        javax.swing.GroupLayout jPAddLayout = new javax.swing.GroupLayout(jPAdd);
        jPAdd.setLayout(jPAddLayout);
        jPAddLayout.setHorizontalGroup(
            jPAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAddLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel16)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPAddLayout.setVerticalGroup(
            jPAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAddLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.add(jPAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 100, 50));

        jPDelete.setBackground(new java.awt.Color(107, 190, 249));
        jPDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPDeleteMouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-orden-de-compra-50.png"))); // NOI18N

        javax.swing.GroupLayout jPDeleteLayout = new javax.swing.GroupLayout(jPDelete);
        jPDelete.setLayout(jPDeleteLayout);
        jPDeleteLayout.setHorizontalGroup(
            jPDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDeleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18))
        );
        jPDeleteLayout.setVerticalGroup(
            jPDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDeleteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15))
        );

        jPanel5.add(jPDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 90, 50));

        pnl_limpar.setBackground(new java.awt.Color(107, 190, 249));
        pnl_limpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_limparMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-escoba-50.png"))); // NOI18N

        javax.swing.GroupLayout pnl_limparLayout = new javax.swing.GroupLayout(pnl_limpar);
        pnl_limpar.setLayout(pnl_limparLayout);
        pnl_limparLayout.setHorizontalGroup(
            pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_limparLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnl_limparLayout.setVerticalGroup(
            pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_limparLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.add(pnl_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 100, 50));

        jPanel6.setBackground(new java.awt.Color(107, 190, 249));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-tabla-40.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(24, 24, 24))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 90, 40));

        jLabel22.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel22.setText("EDITAR FACTURA");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel23.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel23.setText("MOSTRAR TABLA GENERAL");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jLabel24.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel24.setText("LIMPIAR FORMULARIO");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jLabel25.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel25.setText("GENERAR FACTURA");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel26.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel26.setText("ORDEN DE COMPRA");
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBuscarMouseClicked
        try {
            // Aqui es donde se generara la busqueda
            //txt_NumFact.setVisible(true);
            //lbl_id.setVisible(true);
            
            numfact=txtsearch.getText();
            
            Statement stm=Conexion.getConexion().createStatement();
            ResultSet rst=stm.executeQuery("SELECT * from CXC where NumFactura = '"+numfact+"'");
            if(rst.next())
            {
                NumCliente = rst.getInt(2);
                NombreCliente = rst.getString(3);
                importetotal = rst.getDouble(4);
                NombreProyecto = rst.getString(5);  
                date = rst.getDate(6);
                datesum = rst.getDate(7);
                saldoxcobrar = rst.getDouble(8);
                anticipo = rst.getDouble(9);
                Solicitante = rst.getString(10);
                Concepto = rst.getString(11);
                Estatus = rst.getInt(12);
                
                
                
                
                txt_numcliente.setText(String.valueOf(NumCliente));
                txt_numfactura.setText(numfact.trim());
                txt_nomsolicitante.setText(String.valueOf(Solicitante));
                lbl_NCliente.setText(NombreCliente.trim());
                txt_concepto.setText(Concepto.trim());
                txt_total2.setText(String.valueOf(importetotal).trim());
                txt_nombreproyecto.setText(NombreProyecto.trim());
                jdc_Fechaem.setDate(date);
                txt_anticipo.setText(String.valueOf(anticipo));
                lbl_saldoxcobrar.setText(String.valueOf(saldoxcobrar));
                lbl_fpago.setText(String.valueOf(datesum));
                
                if(Estatus == 3){
                    lbl_estatus.setForeground(Color.red);
                    lbl_estatus.setText("CANCELADO");
                } else if(Estatus == 1) {
                    lbl_estatus.setForeground(Color.GREEN);
                    lbl_estatus.setText("PAGADO");
                } else if (Estatus == 2){
                    lbl_estatus.setForeground(Color.yellow);
                    lbl_estatus.setText("PENDIENTE");
                } else {
                    lbl_estatus.setText("Error");
                }
                          
                
            } else {
                JOptionPane.showMessageDialog(null, "El número de Factura no existe","Número no existente",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Panel_CXC_Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPBuscarMouseClicked

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // Busqueda de informacion mediante ID, NOMBRE O RFC

    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased

    }//GEN-LAST:event_txtsearchKeyReleased

    private void txt_nombreproyectoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreproyectoKeyTyped
     /*   if(txt_nombreproyecto.getText().length() >= 3)
        {
            evt.consume();
        }*/
    }//GEN-LAST:event_txt_nombreproyectoKeyTyped

    private void txt_conceptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_conceptoKeyTyped
        /*if(txt_concepto.getText().length() >= 13)
        {
            evt.consume();
        }*/
    }//GEN-LAST:event_txt_conceptoKeyTyped

    private void jPEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEditarMouseClicked
        date = jdc_Fechaem.getDate();
        long d = date.getTime();
        java.sql.Date fechaem = new java.sql.Date(d);
        String fechapago = "";
        String fechaaux = fechaem.toString();
        NumFactura = txt_numfactura.getText();
        importetotal = Double.parseDouble(txt_total2.getText());
        NombreProyecto = txt_nombreproyecto.getText();
        Solicitante = txt_nomsolicitante.getText();
        Concepto = txt_concepto.getText();
        
         if(condpago == 30){
            fechapago = sumarDiasAFecha(fechaaux, 30);
        } else if(condpago == 45){
            fechapago = sumarDiasAFecha(fechaaux, 45);
        } else if(condpago == 60){
            fechapago = sumarDiasAFecha(fechaaux, 60);
        }
       // System.out.println(fechaem);
        
         try {
            
            Statement stm=Conexion.getConexion().createStatement();
            
           
             confirmacion = JOptionPane.showConfirmDialog(null,"¿Esta seguro que desea editar estos datos?");
             if(confirmacion == 0){
                  ResultSet rst=stm.executeQuery("update CXC set NCliente = '"+NumCliente+"', NomCliente ='"+NombreCliente.trim()+"', ImporteTotal = '"+importetotal+"', NombreProj = '"+NombreProyecto.trim()+"', FEmision = '"+fechaem+"', FPago = '"+fechapago+"', Saldo = '"+saldoxcobrar+"', Anticipo = '"+anticipo+"', Solicitante = '"+Solicitante.trim()+"', Concepto = '"+Concepto.trim()+"', Estatus = '"+Estatus+"'where NumFactura = '"+NumFactura+"'");            
             }
            
        
        } catch (SQLException ex) {
            Logger.getLogger(Panel_CXC_Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
         JOptionPane.showMessageDialog(null, "Datos editados con éxito","Datos Gauradados",JOptionPane.INFORMATION_MESSAGE);
         
         confirmacion = JOptionPane.showConfirmDialog(null,"¿Desea modificar otros datos?");
         if(confirmacion == 0){
         }
    }//GEN-LAST:event_jPEditarMouseClicked

    private void jPAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAddMouseClicked
        date = jdc_Fechaem.getDate();
        long d = date.getTime();
        java.sql.Date fechaem = new java.sql.Date(d);
        String fechapago = "";
        String fechaaux = fechaem.toString();
        NumFactura = txt_numfactura.getText();
        importetotal = Double.parseDouble(txt_total2.getText());
        NombreProyecto = txt_nombreproyecto.getText();
        Solicitante = txt_nomsolicitante.getText();
        Concepto = txt_concepto.getText();
        
         if(condpago == 30){
            fechapago = sumarDiasAFecha(fechaaux, 30);
        } else if(condpago == 45){
            fechapago = sumarDiasAFecha(fechaaux, 45);
        } else if(condpago == 60){
            fechapago = sumarDiasAFecha(fechaaux, 60);
        }
       // System.out.println(fechaem);
    
         try {
            
            Statement stm=Conexion.getConexion().createStatement();
            //Llamado a la base de datos
            ResultSet rs=stm.executeQuery("insert into CXC (NumFactura, NCliente, NomCliente, ImporteTotal, NombreProj, FEmision, FPago, Saldo, Anticipo, Solicitante, Concepto, Estatus) values ('"+NumFactura.trim()+"','"+NumCliente+"','"+NombreCliente.trim()+"','"+importetotal+"','"+NombreProyecto.trim()+"','"+fechaem+"', '"+fechapago+"','"+saldoxcobrar+"', '"+anticipo+"', '"+Solicitante+"', '"+Concepto+"', '"+Estatus+"')");
        } catch (SQLException ex) {
            Logger.getLogger(Panel_CXC_Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPAddMouseClicked

    private void jPDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDeleteMouseClicked
        // Eleminacion de un proveedor

    }//GEN-LAST:event_jPDeleteMouseClicked

    private void pnl_limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limparMouseClicked
        // TODO add your handling code here:
        txt_numfactura.setText("");
        txt_nomsolicitante.setText("");
        lbl_NCliente.setText("");
        txt_concepto.setText("");
        txt_nombreproyecto.setText("");
        lbl_fpago.setText("");
        lbl_NCliente.setText("");
        txt_total2.setText("");
        lbl_estatus.setText("");
        chk_cancelado.setEnabled(false);
        lbl_fpago.setText("");
        jdc_Fechaem.setDate(null);
    }//GEN-LAST:event_pnl_limparMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        try {
            // TODO add your handling code here:

            TGeneral tg = new TGeneral();
            tg.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void txt_nomsolicitanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomsolicitanteKeyReleased

    }//GEN-LAST:event_txt_nomsolicitanteKeyReleased

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void txt_nomsolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomsolicitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomsolicitanteActionPerformed

    private void txt_numclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numclienteActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_numclienteActionPerformed

    private void txt_numclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numclienteKeyReleased
        // TODO add your handling code here:
        NumCliente = Integer.parseInt(txt_numcliente.getText());
        if(txt_numcliente.getText() != ""){
         try {
            
            Statement stm=Conexion.getConexion().createStatement();
            //Llamado a la base de datos
            ResultSet rs=stm.executeQuery("Select NomCliente from Clientes where NumCliente = '"+NumCliente+"' ");
            if(rs.next()){
                lbl_NCliente.setForeground(new Color(0,0,0));
                NombreCliente = rs.getString("NomCliente");
                lbl_NCliente.setText(NombreCliente.trim());
            } else {
                lbl_NCliente.setForeground(Color.red);
                lbl_NCliente.setText("Cliente no existente");
            } 
                
        } catch (SQLException ex) {
            Logger.getLogger(Panel_CXC_Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
       } else {
           lbl_NCliente.setText("");
        }
    }//GEN-LAST:event_txt_numclienteKeyReleased

    private void txt_anticipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_anticipoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_anticipoKeyTyped

    private void txt_total2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_total2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total2KeyTyped

    private void txt_anticipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anticipoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_anticipoActionPerformed

    private void chk_canceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_canceladoActionPerformed
        // TODO add your handling code here:
        int confirmacion = JOptionPane.showConfirmDialog(null,"¿Esta seguro que desea cancelar esta factura?");
        if(confirmacion == 0){
            //String motivo = JOptionPane.showInputDialog("¿Cual es el motivo de la cancelación?"); ESTO SE IRA DIRECTAMENTE AL HISTORICO/LOG, CON EL MOTIVO DE CANCELACION Y QUIEN CANCELO (PENDIENTE)
        Estatus = 3;
        lbl_estatus.setForeground(Color.red);
        lbl_estatus.setText("CANCELADO");
        } else {
            chk_cancelado.setSelected(false);
        }
    }//GEN-LAST:event_chk_canceladoActionPerformed

    private void txt_anticipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_anticipoKeyReleased
        // TODO add your handling code here:
        importetotal = Double.parseDouble(txt_total2.getText());
        anticipo = Double.parseDouble(txt_anticipo.getText());
        saldoxcobrar = importetotal - anticipo;
        lbl_saldoxcobrar.setText(String.valueOf(saldoxcobrar));
        if(importetotal == 0 || txt_total2.getText() == ""){
            saldoxcobrar = 0;
            lbl_saldoxcobrar.setText(String.valueOf(saldoxcobrar));
        }
        if(saldoxcobrar == 0){
            Estatus = 1;
            lbl_estatus.setForeground(Color.GREEN);
            lbl_estatus.setText("PAGADO");
        } else {
            Estatus = 2;
            lbl_estatus.setForeground(Color.YELLOW);
            lbl_estatus.setText("PENDIENTE");
        }
    }//GEN-LAST:event_txt_anticipoKeyReleased

    private void chk_150dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_150dActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        condpago = 150;
        date = jdc_Fechaem.getDate();
        long d = date.getTime();
        java.sql.Date fechaem = new java.sql.Date(d);
        String fechapago = "";
        String fechaaux = fechaem.toString();
        System.out.println(fechaem);

        //Ifs para calculo de la fecha de pago
        if(condpago == 30){
            fechapago = sumarDiasAFecha(fechaaux, 30);
        } else if(condpago == 60){
            fechapago = sumarDiasAFecha(fechaaux, 60);
        } else if(condpago == 90){
            fechapago = sumarDiasAFecha(fechaaux, 90);
        } else if(condpago == 120){
            fechapago = sumarDiasAFecha(fechaaux, 120);
        } else if(condpago == 150){
            fechapago = sumarDiasAFecha(fechaaux, 150);
        }
        lbl_fpago.setText(String.valueOf(fechapago));
    }//GEN-LAST:event_chk_150dActionPerformed

    private void chk_60dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_60dActionPerformed
        // TODO add your handling code here:
        condpago = 60;
        date = jdc_Fechaem.getDate();
        long d = date.getTime();
        java.sql.Date fechaem = new java.sql.Date(d);
        String fechapago = "";
        String fechaaux = fechaem.toString();
        System.out.println(fechaem);

        //Ifs para calculo de la fecha de pago
        if(condpago == 30){
            fechapago = sumarDiasAFecha(fechaaux, 30);
        } else if(condpago == 60){
            fechapago = sumarDiasAFecha(fechaaux, 60);
        } else if(condpago == 90){
            fechapago = sumarDiasAFecha(fechaaux, 90);
        } else if(condpago == 120){
            fechapago = sumarDiasAFecha(fechaaux, 120);
        } else if(condpago == 150){
            fechapago = sumarDiasAFecha(fechaaux, 150);
        }
        lbl_fpago.setText(String.valueOf(fechapago));
    }//GEN-LAST:event_chk_60dActionPerformed

    private void chk_90dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_90dActionPerformed
        // TODO add your handling code here:
        condpago = 90;
        date = jdc_Fechaem.getDate();
        long d = date.getTime();
        java.sql.Date fechaem = new java.sql.Date(d);
        String fechapago = "";
        String fechaaux = fechaem.toString();
        System.out.println(fechaem);

        //Ifs para calculo de la fecha de pago
        if(condpago == 30){
            fechapago = sumarDiasAFecha(fechaaux, 30);
        } else if(condpago == 60){
            fechapago = sumarDiasAFecha(fechaaux, 60);
        } else if(condpago == 90){
            fechapago = sumarDiasAFecha(fechaaux, 90);
        } else if(condpago == 120){
            fechapago = sumarDiasAFecha(fechaaux, 120);
        } else if(condpago == 150){
            fechapago = sumarDiasAFecha(fechaaux, 150);
        }
        lbl_fpago.setText(String.valueOf(fechapago));
    }//GEN-LAST:event_chk_90dActionPerformed

    private void chk_inmediatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_inmediatoActionPerformed
        // TODO add your handling code here:
        date = jdc_Fechaem.getDate();
        long d = date.getTime();
        java.sql.Date fechaem = new java.sql.Date(d);
        String fechapago = "";
        String fechaaux = fechaem.toString();
        System.out.println(fechaem);
        fechapago = fechaaux;
        lbl_fpago.setText(String.valueOf(fechapago));

    }//GEN-LAST:event_chk_inmediatoActionPerformed

    private void txt_total2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total2ActionPerformed

    private void chk_30dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_30dActionPerformed
        // TODO add your handling code here:
        condpago = 30;
        date = jdc_Fechaem.getDate();
        long d = date.getTime();
        java.sql.Date fechaem = new java.sql.Date(d);
        String fechapago = "";
        String fechaaux = fechaem.toString();
        System.out.println(fechaem);

        //Ifs para calculo de la fecha de pago
        if(condpago == 30){
            fechapago = sumarDiasAFecha(fechaaux, 30);
        } else if(condpago == 60){
            fechapago = sumarDiasAFecha(fechaaux, 60);
        } else if(condpago == 90){
            fechapago = sumarDiasAFecha(fechaaux, 90);
        } else if(condpago == 120){
            fechapago = sumarDiasAFecha(fechaaux, 120);
        } else if(condpago == 150){
            fechapago = sumarDiasAFecha(fechaaux, 150);
        }
        lbl_fpago.setText(String.valueOf(fechapago));
    }//GEN-LAST:event_chk_30dActionPerformed

    private void chk_120dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_120dActionPerformed
        // TODO add your handling code here:
        condpago = 120;
        date = jdc_Fechaem.getDate();
        long d = date.getTime();
        java.sql.Date fechaem = new java.sql.Date(d);
        String fechapago = "";
        String fechaaux = fechaem.toString();
        System.out.println(fechaem);

        //Ifs para calculo de la fecha de pago
        if(condpago == 30){
            fechapago = sumarDiasAFecha(fechaaux, 30);
        } else if(condpago == 60){
            fechapago = sumarDiasAFecha(fechaaux, 60);
        } else if(condpago == 90){
            fechapago = sumarDiasAFecha(fechaaux, 90);
        } else if(condpago == 120){
            fechapago = sumarDiasAFecha(fechaaux, 120);
        } else if(condpago == 150){
            fechapago = sumarDiasAFecha(fechaaux, 150);
        }
        lbl_fpago.setText(String.valueOf(fechapago));
    }//GEN-LAST:event_chk_120dActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupAnticipo;
    private javax.swing.ButtonGroup btnGroupCondPago;
    private javax.swing.JCheckBox chk_120d;
    private javax.swing.JCheckBox chk_150d;
    private javax.swing.JCheckBox chk_30d;
    private javax.swing.JCheckBox chk_60d;
    private javax.swing.JCheckBox chk_90d;
    private javax.swing.JCheckBox chk_cancelado;
    private javax.swing.JCheckBox chk_inmediato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPAdd;
    private javax.swing.JPanel jPBuscar;
    private javax.swing.JPanel jPDelete;
    private javax.swing.JPanel jPEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private com.toedter.calendar.JDateChooser jdc_Fechaem;
    private javax.swing.JLabel lbl_NCliente;
    private javax.swing.JLabel lbl_estatus;
    private javax.swing.JLabel lbl_estatustitulo;
    private javax.swing.JLabel lbl_fpago;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_saldoxcobrar;
    private javax.swing.JPanel pnl_limpar;
    private javax.swing.JTextField txt_anticipo;
    private javax.swing.JTextField txt_concepto;
    private javax.swing.JTextField txt_nombreproyecto;
    private javax.swing.JTextField txt_nomsolicitante;
    private javax.swing.JTextField txt_numcliente;
    private javax.swing.JTextField txt_numfactura;
    private javax.swing.JTextField txt_total2;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
