/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Proveedores;

import Proveedores.*;
import ConexionBD.Conexion;
import Log.Login;

import com.microsoft.sqlserver.jdbc.SQLServerDataSource;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author Mike
 */
public class Proveedores_Principal extends javax.swing.JPanel {

    /**
     * Creates new form Proveedores_Principal
     */
    UIManager UI=new UIManager();
    static String usuario;
    
    public Proveedores_Principal(String usuario) {
        initComponents();
        this.usuario=usuario;
        txtID.setVisible(false);
        //lblNOMBRE.setVisible(false);
        lblmsgwarning.setVisible(false);
         ImageIcon icon;
                        icon = new ImageIcon("Iconografias/icons8-signo-de-interrogación-50.png");
                        lbl_infoc.setText("Este cliente no tiene constancia");
                        lbl_infoc.setForeground(Color.red);
                        lbl_estatusconstancia.setIcon(icon);
    }
    
    static int confirmacion;
    public String VALORPROV; //Ya sea lo que sea escrito en el txt de busqueda se generara el query 
    public String IDPROV;
    public String NOMPROV;
    public String RFCPROV;
    public String NOMCALLEPROV;
    public String NIPROV;
    public String NEPROV;
    public String ESTPROV;
    public String MUNPROV;
    public String COLPROV;
    public String CPPROV;    
    public String TELPROV;
    public String EMAILPROV;
    InputStream is;
    FileInputStream fis;
    int longitudBytes;
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void borrado(String valor) throws SQLException
    {
    Statement stm=Conexion.getConexion().createStatement();
    ResultSet rs=stm.executeQuery("delete Proveedores where NumProveedor='"+valor+"';"); 
                   
    }
    public void GENH(String mensaje1, String mensaje2) throws SQLException
    {
    Login log= new Login();
    //String mensaje3=log.u;
    
    Date fecha = new Date();
    long flong = fecha.getTime();
    java.sql.Date fechaing = new java.sql.Date(flong);
        
    DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
    Date date = new Date();
    
    Statement stm=Conexion.getConexion().createStatement();
    
    ResultSet rs=stm.executeQuery("insert HG (NOMUSUARIO,FECHA,ACCION,NG,HORA,MOTIVO) values ('"+usuario+"','"+fechaing+"','"+mensaje1+"','"+mensaje2+"','"+dateFormat.format(date)+"','-');");
    }
    public void AnadirDomicilio() throws SQLException{
        Statement stm=Conexion.getConexion().createStatement();
        ResultSet rs=stm.executeQuery("select top(1)  NumProveedor from Proveedores order by NumProveedor desc");
        if(rs.next())
        {
                        
        //PRUEBA DE DATOS EXISTENTES EN LAS VARIABLES DE MI CLASE     
        IDPROV=rs.getString(1);
        System.out.println(IDPROV);
        System.out.println(NOMPROV);
        System.out.println(RFCPROV);
        System.out.println(NOMCALLEPROV);
        System.out.println(NIPROV);
        System.out.println(NEPROV);
        System.out.println(ESTPROV);
        System.out.println(MUNPROV);
        System.out.println(COLPROV);
        System.out.println(CPPROV);
        System.out.println(TELPROV);
        //System.out.println(EMAILPROV);*/
        JOptionPane.showMessageDialog(null, "Su numero de indentificador es :"+IDPROV, "INFORMACION ADICIONAL", JOptionPane.INFORMATION_MESSAGE,
        new ImageIcon("src/Iconografias/icons8-id-de-la-cara-50.png"));
             //JOptionPane.showMessageDialog(null,"Su identificador es:"+IDPROV);
        /*rs=stm.executeQuery("insert into DomProveedores (Num_Proveedor,Nombre_Calle,Num_Ext,Num_Int,Estado,Municipio,Colonia, CP,Telefono,email) "
        + "values('"+Integer.parseInt(IDPROV)+"','"+NOMCALLEPROV+"','"+NEPROV+"','"+NIPROV+"','"+ESTPROV+"','"+MUNPROV+"','"+COLPROV+"','"+CPPROV+"','"+Integer.parseInt(TELPROV)+"','"+EMAILPROV+"')");
        */
        rs=stm.executeQuery("insert into DomProveedores (Num_Proveedor,Nombre_Calle,Num_Ext,Num_Int,Estado,Municipio,Colonia, CP,Telefono,email) "
        + "values('"+IDPROV+"','"+NOMCALLEPROV+"','"+NEPROV+"','"+NIPROV+"','"+ESTPROV+"','"+MUNPROV+"','"+COLPROV+"','"+CPPROV+"','"+TELPROV+"','"+EMAILPROV+"')");
             }
        //rs=stm.executeQuery("insert into ");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNOMBRE = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNEX = new javax.swing.JTextField();
        txtNI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCOL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtCALLE = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMunicipio1 = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_estatusconstancia = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        lbl_infoc = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPEditar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPAdd = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPDelete = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pnl_limpar = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        JPCB = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPBuscar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        lblmsgwarning = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(950, 750));

        jPanel1.setBackground(new java.awt.Color(140, 140, 140));
        jPanel1.setPreferredSize(new java.awt.Dimension(810, 442));

        lblNOMBRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNOMBRE.setForeground(new java.awt.Color(255, 255, 255));
        lblNOMBRE.setText("NOMBRE / RAZON SOCIAL");

        txtID.setEditable(false);
        txtID.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono");

        txtTel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Num Exterior");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Num interior");

        txtNEX.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNEX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNEXKeyTyped(evt);
            }
        });

        txtNI.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNIKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Colonia");

        txtCOL.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCOL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCOLKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Codigo Postal");

        txtCP.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre de calle");

        txtRFC.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFCKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estado");

        txtEstado.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("E-MAIL");

        txtemail.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtCALLE.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCALLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCALLEActionPerformed(evt);
            }
        });
        txtCALLE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCALLEKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Municipio");

        txtMunicipio1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMunicipio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMunicipio1ActionPerformed(evt);
            }
        });
        txtMunicipio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMunicipio1KeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("RFC");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_estatusconstancia, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_estatusconstancia, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Cargar constancia ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_infoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_infoc.setForeground(new java.awt.Color(255, 255, 255));
        lbl_infoc.setText("CONSTANCIA DE SITUACIÓN FISCAL");

        lbl_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("Código de identificación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(lbl_infoc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNEX, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtNI, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtMunicipio1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtCALLE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCOL, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNOMBRE)
                    .addComponent(lbl_infoc))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel17))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMunicipio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCALLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCOL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(107, 190, 249));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPEditar.setBackground(new java.awt.Color(107, 190, 249));
        jPEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPEditarMouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-editar-50.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPEditarLayout = new javax.swing.GroupLayout(jPEditar);
        jPEditar.setLayout(jPEditarLayout);
        jPEditarLayout.setHorizontalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEditarLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(19, 19, 19))
        );
        jPEditarLayout.setVerticalGroup(
            jPEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEditarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14))
        );

        jPanel5.add(jPEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 90, -1));

        jPAdd.setBackground(new java.awt.Color(107, 190, 249));
        jPAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPAddMouseExited(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-añadir-usuario-masculino-50.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPAddLayout = new javax.swing.GroupLayout(jPAdd);
        jPAdd.setLayout(jPAddLayout);
        jPAddLayout.setHorizontalGroup(
            jPAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAddLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel16)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPAddLayout.setVerticalGroup(
            jPAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAddLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.add(jPAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 90, -1));

        jPDelete.setBackground(new java.awt.Color(107, 190, 249));
        jPDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPDeleteMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-borrar-para-siempre-50.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPDeleteLayout = new javax.swing.GroupLayout(jPDelete);
        jPDelete.setLayout(jPDeleteLayout);
        jPDeleteLayout.setHorizontalGroup(
            jPDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDeleteLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(20, 20, 20))
        );
        jPDeleteLayout.setVerticalGroup(
            jPDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDeleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        jPanel5.add(jPDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 90, 60));

        pnl_limpar.setBackground(new java.awt.Color(107, 190, 249));
        pnl_limpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_limparMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_limparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_limparMouseExited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-escoba-50.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnl_limparLayout = new javax.swing.GroupLayout(pnl_limpar);
        pnl_limpar.setLayout(pnl_limparLayout);
        pnl_limparLayout.setHorizontalGroup(
            pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limparLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl_limparLayout.setVerticalGroup(
            pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnl_limparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_limparLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel5.add(pnl_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 100, 50));

        jPanel6.setBackground(new java.awt.Color(107, 190, 249));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-tabla-40.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(44, 44, 44))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 130, 50));

        jLabel20.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel20.setText("EDITAR USUARIO");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel21.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel21.setText("MOSTRAR TABLA GENERAL");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        jLabel23.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel23.setText("LIMPIAR FORMULARIO");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        jLabel24.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel24.setText("GENERAR NUEVO PROVEEDOR");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabel25.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel25.setText("ELIMINAR USUARIO");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Antique Olive", 1, 24)); // NOI18N
        jLabel18.setText("MENU PRINCIPAL DE PROVEEDORES");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(239, 239, 239))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPCB.setBackground(new java.awt.Color(140, 140, 140));

        jPanel4.setBackground(new java.awt.Color(140, 140, 140));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jPBuscar.setBackground(new java.awt.Color(140, 140, 140));
        jPBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPBuscarMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografias/icons8-búsqueda-50 (1).png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPBuscarLayout = new javax.swing.GroupLayout(jPBuscar);
        jPBuscar.setLayout(jPBuscarLayout);
        jPBuscarLayout.setHorizontalGroup(
            jPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPBuscarLayout.setVerticalGroup(
            jPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        lblmsgwarning.setFont(new java.awt.Font("Rockwell", 3, 12)); // NOI18N
        lblmsgwarning.setForeground(new java.awt.Color(255, 0, 51));
        lblmsgwarning.setText("¡DEBES COLOCAR INFORMACIÓN PARA GENERAR UNA BUSQUEDA!");

        javax.swing.GroupLayout JPCBLayout = new javax.swing.GroupLayout(JPCB);
        JPCB.setLayout(JPCBLayout);
        JPCBLayout.setHorizontalGroup(
            JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPCBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmsgwarning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPCBLayout.setVerticalGroup(
            JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPCBLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(JPCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JPCBLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(JPCBLayout.createSequentialGroup()
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblmsgwarning))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(JPCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // Busqueda de informacion mediante ID, NOMBRE O RFC

       
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
      
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jPEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEditarMouseClicked
        // Editar la informacion 
            IDPROV=txtID.getText();
            NOMPROV=txtNom.getText();
            RFCPROV=txtRFC.getText();
            NOMCALLEPROV=txtCALLE.getText();
            NIPROV=txtNI.getText();
            NEPROV=txtNEX.getText();
            ESTPROV=txtEstado.getText();
            MUNPROV=txtMunicipio1.getText();
            COLPROV=txtCOL.getText();
            TELPROV=txtTel.getText();
            CPPROV=txtCP.getText();
            EMAILPROV=txtemail.getText();            
           // System.out.println(""+IDPROV+""+NOMPROV+""+RFCPROV);
        try {
            Statement stm=(Statement) Conexion.getConexion().createStatement();     
            ResultSet rs;
            rs = stm.executeQuery("select NumProveedor"
                    + ",Nombre, "
                    + "RFC, "
                    + "Constancia, "
                    + "Nombre_Calle, "
                    + "Num_Int, "
                    + "Num_Ext, "
                    + "Estado, "
                    + "Municipio, "
                    + "Colonia, "
                    + "CP, "
                    + "Telefono, "   
                    + "email "
                    + "FROM Proveedores inner join DomProveedores on Proveedores.NumProveedor=DomProveedores.Num_Proveedor "
                    + "where RFC = '"+RFCPROV+"' or Nombre like '%"+NOMPROV+"%'");            
            if(rs.next()!=false)
            {
            JOptionPane.showMessageDialog(null,"Sus datos no pueden ser modificados");
            }
            else
            {
                String sql="UPDATE Proveedores set Nombre = ?, RFC = ?, Constancia = ? where NumProveedor ="+IDPROV;

                PreparedStatement ps=Conexion.getConexion().prepareStatement(sql);
            //ps.setInt(1,Integer.parseInt(txtcodigo.getText()));
                 ps.setString(1,NOMPROV);
                 ps.setString(2, RFCPROV);
                 ps.setBinaryStream(3,fis,longitudBytes);
                 ps.execute();
                 ps.close();
                rs=stm.executeQuery("update DomProveedores set Nombre_Calle='"+NOMCALLEPROV+"', Num_Ext='"+NEPROV+"', Num_Int='"+NIPROV+"', Estado='"+ESTPROV+"', Municipio='"+MUNPROV+"', Colonia='"+COLPROV+"', CP='"+CPPROV+"', Telefono='"+TELPROV+"', email='"+EMAILPROV+"' "
                        + "where Num_Proveedor ='"+IDPROV+"';");
            } 
        
        
        } catch (SQLException ex) {
          Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try 
        {
        GENH("Modificación en los datos del proveedor",IDPROV);
        } catch (SQLException ex) 
        {
            Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
        
    }//GEN-LAST:event_jPEditarMouseClicked

    private void txtRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCKeyTyped
        if(txtRFC.getText().length() >= 13)
        {
        evt.consume();
        }
    }//GEN-LAST:event_txtRFCKeyTyped

    private void jPDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDeleteMouseClicked
        // Eleminacion de un proveedor  
       // int d;
        IDPROV=txtID.getText();
        NOMPROV=txtNom.getText();
        RFCPROV=txtRFC.getText();
        NOMCALLEPROV=txtCALLE.getText();
        NIPROV=txtNI.getText();
        NEPROV=txtNEX.getText();
        ESTPROV=txtEstado.getText();
        MUNPROV=txtMunicipio1.getText();
        COLPROV=txtCOL.getText();
        CPPROV=txtCP.getText();
        TELPROV=txtTel.getText();
        EMAILPROV=txtemail.getText();
       
  try {      
            Statement stm=(Statement) Conexion.getConexion().createStatement();     
            ResultSet rs;  

            /*int d= Integer.parseInt(JOptionPane.showInputDialog(null, "¿Desea eliminar los datos de "+NOMPROV+"?"
               + "\nIDENTIFICADOR:"+IDPROV+""
               + "\nRFC:"+RFCPROV+""
               + "\nTELPROV:"+TELPROV+""
               + "\nEMAIL:"+EMAILPROV+""
               + "\nCODIGO POSTAL:"+CPPROV+""
               + "", "CONFIRMACIÓN", HEIGHT,  new ImageIcon("src/Iconografias/icons8-borrar-para-siempre-50.png")));    */
            //int d = Integer.parseInt(JOptionPane.showInputDialog(null, "¿Desea eliminar los datos de ?"
             //   , "CONFIRMACIÓN", HEIGHT, new ImageIcon("src/Iconografias/icons8-borrar-para-siempre-50.png"), null, 0));
            //        int d=Integer.parseInt( JOptionPane.showInputDialog(null, "¿Desea eliminar los datos?", "ENTRADA DE DATOS", JOptionPane.OK_CANCEL_OPTION, 
             //   new ImageIcon("src/iconos/icons8-tabla-40.png"), , 0));       

           // d = Integer.parseInt(JOptionPane.showConfirmDialog(null, "¿Desea eliminar los datos?", "CONFIRMACIÓN", JOptionPane.YES_NO_CANCEL_OPTION);
           // e=Integer.parseInt(JOptionPane.showConfirmDialog(mull, "a", NIPROV, WIDTH, HEIGHT, icon);
                   ImageIcon icono = new ImageIcon("src/Iconografias/icons8-borrar-para-siempre-50.png");
                   int resp =JOptionPane.showConfirmDialog(null, "¿Desea eliminar los datos?",
                "CONFIRMACIÓN", JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE, icono);
             
             //showConfirmDialog(null, "¿Desea eliminar los datos?", "Confirmación", JOptionPane.DEFAULT_OPTION,
              //     new ImageIcon("src/Iconografias/icons8-borrar-para-siempre-50.png")));
            System.out.println(resp);
              if (resp==0)
                        {
                JOptionPane.showMessageDialog(null, "Datos eliminados correctamente", "OPERACIÓN EXITOSA", JOptionPane.INFORMATION_MESSAGE,
                new ImageIcon("src/Iconografias/icons8-borrar-para-siempre-50.png"));
                rs=stm.executeQuery("DELETE  DomProveedores where  Num_Proveedor='"+IDPROV+"';");
                rs=stm.executeQuery("delete Proveedores where NumProveedor='"+IDPROV+"';");
                       }
        else if (resp==1)
       {
           JOptionPane.showMessageDialog(null,"Eliminación cancelada");
       }
            } catch (SQLException ex) {
                Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

        try 
        {
            borrado(IDPROV);
        } catch (SQLException ex) 
        {
            Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        try 
        {
            GENH("Borrado del proveedor",NOMPROV);
        } catch (SQLException ex) 
        {
            Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
           

        
        
    }//GEN-LAST:event_jPDeleteMouseClicked

    private void jPAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAddMouseClicked
        //EVENTO PARA AGREGAR DATOS A LA BD 
    UI.put("OptionPane.background",new ColorUIResource(107, 190, 249));
    UI.put("Panel.background",new ColorUIResource(107, 190, 249));
    UI.put("Button.background", new ColorUIResource(74, 157, 206));
    UI.put("Button.foreground", new ColorUIResource(0, 0, 0));
    UI.put("OptionPane.messageFont", new FontUIResource(new Font( "Segoe UI", Font.BOLD, 13))); 
    NOMPROV=txtNom.getText();
    RFCPROV=txtRFC.getText();
    NOMCALLEPROV=txtCALLE.getText();
    NIPROV=txtNI.getText();
    NEPROV=txtNEX.getText();
    ESTPROV=txtEstado.getText();
    MUNPROV=txtMunicipio1.getText();
    COLPROV=txtCOL.getText();
    CPPROV=txtCP.getText();
    TELPROV=txtTel.getText();
    EMAILPROV=txtemail.getText();
        try 
        {
        Statement stm=Conexion.getConexion().createStatement();
        
        ResultSet rs=stm.executeQuery("select * from Proveedores where RFC like '%"+RFCPROV+"%' or Nombre ='"+NOMPROV+"'");  
            if (rs.next()==false)
            {
            JOptionPane.showMessageDialog(null, "¡Datos agregados a la base de datos correctamente!", "OPERACIÓN EXITOSA", JOptionPane.INFORMATION_MESSAGE,
            new ImageIcon("src/Iconografias/icons8-de-acuerdo-50.png"));
            String sql="INSERT INTO Proveedores (Nombre, RFC, Constancia) VALUES (?, ?, ?)";

             PreparedStatement ps=Conexion.getConexion().prepareStatement(sql);
            //ps.setInt(1,Integer.parseInt(txtcodigo.getText()));
            ps.setString(1,NOMPROV);
            ps.setString(2,RFCPROV);
            ps.setBinaryStream(3,fis,longitudBytes);
            ps.execute();
            ps.close();

            }
            else 
            {
           JOptionPane.showMessageDialog(null,"Su operación no puede realizarse!");
            }
        } catch (SQLException ex) 
        {
            Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }   
        try 
        {
            AnadirDomicilio();
        } catch (SQLException ex) 
        {
            Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try 
        {
            GENH("Generacion de proveedor",NOMPROV);
        } catch (SQLException ex) 
        {
            Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jPAddMouseClicked

    private void pnl_limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limparMouseClicked
        // TODO add your handling code here:
        limpiar();
        txtID.setVisible(false);
        lblNOMBRE.setVisible(false);
    }//GEN-LAST:event_pnl_limparMouseClicked

    private void jPBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBuscarMouseClicked
 //busqueda de datos tanto bancarios como datos principales del proveedor 
        ImageIcon foto;
        VALORPROV=txtsearch.getText();
        lbl_estatusconstancia.setIcon(null);
        System.out.println("valor obtenido"+VALORPROV+"a");
 
        SQLServerDataSource con = new SQLServerDataSource();
        con.setServerName("localhost");
        con.setDatabaseName("Gestion4F");
        con.setUser("4FAdmin"); //CAMBIO 
        con.setPassword("CuatroF");
        con.setPortNumber(1433);
       
            try {
                String url = "select * FROM Proveedores inner join DomProveedores on Proveedores.NumProveedor=DomProveedores.Num_Proveedor where NumProveedor ="+txtsearch.getText();
                Connection cn = con.getConnection();
                PreparedStatement ps = cn.prepareStatement(url);
                ResultSet rst = ps.executeQuery();

            while(rst.next())
            {
                IDPROV=rst.getString(1);
                NOMPROV=rst.getString(2);
                RFCPROV=rst.getString(3);
                NOMCALLEPROV=rst.getString(5);
                NIPROV=rst.getString(6);
                NEPROV=rst.getString(7);
                ESTPROV=rst.getString(8);
                MUNPROV=rst.getString(9);
                COLPROV=rst.getString(10);
                CPPROV =rst.getString(11);
                TELPROV=rst.getString(12);
                EMAILPROV=rst.getString(13);
                is = rst.getBinaryStream(4);

                txtID.setText(IDPROV.trim());
                txtNom.setText(NOMPROV.trim());
                txtRFC.setText(RFCPROV.trim());
                txtCALLE.setText(NOMCALLEPROV.trim());
                txtNI.setText(NIPROV.trim());
                txtNEX.setText(NEPROV.trim());
                txtEstado.setText(ESTPROV.trim());
                txtMunicipio1.setText(MUNPROV.trim());
                txtCOL.setText(COLPROV.trim());
                txtCP.setText(CPPROV.trim());
                txtTel.setText(TELPROV.trim());
                txtemail.setText(EMAILPROV.trim());
                
                if(is != null){
                        BufferedImage bi = ImageIO.read(is);
                         foto = new ImageIcon(bi);
                         System.out.println(bi);
                         Image img = foto.getImage();
                         Image newimg = img.getScaledInstance(140, 170, java.awt.Image.SCALE_SMOOTH);
                
                         ImageIcon newicon = new ImageIcon(newimg);
                
                         lbl_estatusconstancia.setIcon(newicon);
 
                        lbl_infoc.setText("Ver Constancia");
                        lbl_infoc.setForeground(Color.green);
                    } else {
                        ImageIcon icon;
                        icon = new ImageIcon("Iconografias/icons8-signo-de-interrogación-50.png");
                       lbl_infoc.setText("Este cliente no tiene constancia");
                        lbl_infoc.setForeground(Color.red);
                       lbl_infoc.setIcon(icon);
                    }

            }
            } catch (SQLException ex) {
                Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
            Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
            


    }//GEN-LAST:event_jPBuscarMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        try {
            // TODO add your handling code here:

            TGeneral tg = new TGeneral();
            tg.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Proveedores_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBuscarMouseEntered
     jPBuscar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPBuscarMouseEntered

    private void jPBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBuscarMouseExited
      jPBuscar.setBackground(new java.awt.Color(140,140,140));
    }//GEN-LAST:event_jPBuscarMouseExited

    private void jPEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEditarMouseEntered
     jPEditar.setBackground(Color.red);
    }//GEN-LAST:event_jPEditarMouseEntered

    private void jPEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEditarMouseExited
     jPEditar.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_jPEditarMouseExited

    private void jPDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDeleteMouseEntered
     jPDelete.setBackground(Color.red);
    }//GEN-LAST:event_jPDeleteMouseEntered

    private void jPDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPDeleteMouseExited
    jPDelete.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_jPDeleteMouseExited

    private void jPAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAddMouseEntered
    jPAdd.setBackground(Color.red);
    }//GEN-LAST:event_jPAddMouseEntered

    private void jPAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAddMouseExited
    jPAdd.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_jPAddMouseExited

    private void pnl_limparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limparMouseEntered
    pnl_limpar.setBackground(Color.red);
    }//GEN-LAST:event_pnl_limparMouseEntered

    private void pnl_limparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_limparMouseExited
    pnl_limpar.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_pnl_limparMouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
    jPanel6.setBackground(Color.red);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
    jPanel6.setBackground(new java.awt.Color(107, 190, 249));
    }//GEN-LAST:event_jPanel6MouseExited

    private void txtCPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPKeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
        if(txtCP.getText().length() >= 5)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtCPKeyTyped

    private void txtCALLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCALLEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCALLEActionPerformed

    private void txtMunicipio1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMunicipio1KeyTyped
        if(Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }        
        if(txtMunicipio1.getText().length() >= 15)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtMunicipio1KeyTyped

    private void txtMunicipio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMunicipio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMunicipio1ActionPerformed

    private void txtNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIKeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
        if(txtNI.getText().length() >= 3)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNIKeyTyped

    private void txtNEXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNEXKeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
        if(txtNEX.getText().length() >= 3)
        {
            evt.consume();
        }

    }//GEN-LAST:event_txtNEXKeyTyped

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        try{
        if(is == null){
                     lbl_estatusconstancia.setIcon(null);
                     JFileChooser j=new JFileChooser();
                     j.setFileSelectionMode(JFileChooser.FILES_ONLY);//solo archivos y no carpetas
                     int estado=j.showOpenDialog(null);
                     if(estado== JFileChooser.APPROVE_OPTION){
            try{
                    fis=new FileInputStream(j.getSelectedFile());
                    //necesitamos saber la cantidad de bytes
                    this.longitudBytes=(int)j.getSelectedFile().length();
                    try {
                    Image icono=ImageIO.read(j.getSelectedFile()).getScaledInstance
                        (lbl_estatusconstancia.getWidth(),lbl_estatusconstancia.getHeight(),Image.SCALE_DEFAULT);
                    lbl_estatusconstancia.setIcon(new ImageIcon(icono));
                    lbl_estatusconstancia.updateUI();

                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "imagen: "+ex);
               }
            }catch(FileNotFoundException ex){
                ex.printStackTrace();
            }
        }
                    } else {
                        ImageIcon icon;
                        icon = new ImageIcon("Iconografias/icons8-marca-de-verificación-50.png");
                        lbl_infoc.setText("VER CONSTANCIA");
                        lbl_infoc.setForeground(Color.green);
                        lbl_estatusconstancia.setIcon(icon);
                    }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"exception: "+ex);
        }
    }//GEN-LAST:event_jPanel8MouseClicked

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
            if(!Character.isDigit(evt.getKeyChar()))
            {
                evt.consume();
            }
            if(txtTel.getText().length() >= 12)
            {
            evt.consume();
            }
    }//GEN-LAST:event_txtTelKeyTyped

    private void txtEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyTyped
        if(Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtEstadoKeyTyped

    private void txtCALLEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCALLEKeyTyped
        if(Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }    
    }//GEN-LAST:event_txtCALLEKeyTyped

    private void txtCOLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCOLKeyTyped
        if(Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }  
    }//GEN-LAST:event_txtCOLKeyTyped

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked
    public void limpiar()
    {
        txtID.setText("");
        txtNom.setText("");
        txtRFC.setText("");
        txtCALLE.setText("");
        txtNI.setText("");
        txtNEX.setText("");
        txtEstado.setText("");
        txtMunicipio1.setText("");
        txtCOL.setText("");
        txtCP.setText("");
        txtTel.setText("");
        txtemail.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPCB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPAdd;
    private javax.swing.JPanel jPBuscar;
    private javax.swing.JPanel jPDelete;
    private javax.swing.JPanel jPEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblNOMBRE;
    private javax.swing.JLabel lbl_estatusconstancia;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_infoc;
    private javax.swing.JLabel lblmsgwarning;
    private javax.swing.JPanel pnl_limpar;
    private javax.swing.JTextField txtCALLE;
    private javax.swing.JTextField txtCOL;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMunicipio1;
    private javax.swing.JTextField txtNEX;
    private javax.swing.JTextField txtNI;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
